= Christian Radicals

[%hardbreaks]
* One Nation Under God: How Corporate America Invented Christian America, by Kevin M. Kruse
* The Scheme: How the Right Wing Used Dark Money to Capture the Supreme Court by Senator Sheldon Whitehouse, Jennifer Mueller
* Democracy in Chains: the deep history of the radical right's stealth plan for America by Nancy MacLean
* The Money Cult: Capitalism, Christianity, and the Unmaking of the American Dream by Chris Lehmann
* Shadow Network: Media, Money, and the Secret Hub of the Radical Right by Anne Nelson
* Dark Money: The Hidden History of the Billionaires Behind the Rise of the Radical Right by Jane Mayer
* Jesus and John Wayne: How White Evangelicals Corrupted a Faith and Fractured a Nation by Kristin Kobes Du Mez
* The Power Worshippers: Inside the Dangerous Rise of Religious Nationalism by Katherine Stewart
* The Kingdom, the Power, and the Glory: American Evangelicals in an Age of Extremism by Tim Alberta
* Die Brandstifter: Wie Extremisten die Republikanische Partei übernahmen by Annika Brockschmidt
* Amerikas Gotteskrieger: Wie die Religiöse Rechte die Demokratie gefährdet by Annika Brockschmidt
