= {subject}
Jan H. Krueger <test@example.com>
:subject: Heritage Armors
:description:  Collection how to get the different Hertiage Armors in World of Warcraft
:doctype: book
:confidentiality: Open
:listing-caption: Listing
:toc:
:toclevels: 6

## Blutelfen: Tradition der Blutelfen

### Vorbedingung
Level 60 Blutelf, Ehrführchtig bei Silbermond

### Startquest
"Der Stolz der Sin'dorei", Vergeben von Botschafterin Morgenschwur in Orgrimmar, ausserhalb der Botschaft.

## Blutelfen: Blutpaladin

### Vorbedingung
Level 60 Blutelf, Ehrführchtig

### Startquest
"Gerufen von der Matriarchin", vergeben von Lady Liadrin am äußeren Ring von Oribos.

## Dunkeleisenzwerge: Tradition der Dunkeleisenzwerge

### Vorbedingung
Level 50, Dunkeleisenzwerg

### Startquest
"Tradition der Dunkeleisenzwerge", vergeben von Ambossthan Thurgaden in Schwarzfelstiefen

## Dunkeleisenzwerge: Arsenal: Lavaschmiedewaffen

### Startquest
"Dunkeleisenwaffen", vergeben von Ambossthan Thurgaden in Schwarzfelstiefen

### Vorbedingung
Level 50, Dunkeleisenzwerg

## Jäger: Anpassungen des dunklen Waldläufers

### Vorbedingung
Erhalt des Erfolges: "Rückkehr nach Lordaeron", Jäger

### Startquest
"Berufung nach Lordaeron", vergeben von Calia Menethil in Oribos

## Mechagnome: Tradition der Mechagnome

### Vorbedingung
Level 50, Mechagnom

### Startquest
"Tradition der Mechagnome", vergeben von ? in Sturmwind