:source-highlighter: highlight.js
== Aylisaftan

Aylisaftan verkörpert die ganz Wildheit der Natur und der Tiere. Er hasst die Menschen und anderen „zivilisierten“ Völker und steht für das Rohe, die Triebe. Er schickt Krankheiten in Tiere, um diejenigen damit zu infizieren und zu Töten, die diese Tiere erjagt, geschlachtet und getötet haben. Aylisaftan empfindet keine Emotionen, außer Hass und Gleichgültigkeit, somit steht er auch für die pure Willkür im Wandel. Er überrascht ahnungslose Wanderer durch ein Wolfsrudel, in das seine Geschöpfe gefahren sind, wodurch irgendwann das Gerücht entstand, Wölfe würden über alle herfallen, die des Nachts reisen. Ebenso sorgt er dafür, dass Pferde durchgehen, Schafe, Ziegen und Kühe verschwinden, da er diese in die Freiheit entlässt. Zumeist wird er in arkanen Studien oder Tempeln der Larja als Elf dargestellt, in typischer Jagdkleidung und mit einem Bogen, allerdings mit tiefschwarzen, leeren Augen, oder als aufrecht gehender Bär mit menschlichem Kopf. Es wird zurzeit erforscht, ob ein Zusammenhang zwischen Aylisaftan und den „tierischen“ Monstern, also in erster Linie Riesenspinnen, Riesenratten und Stubenfliegen besteht.

=== Anhängerschaft
Die Anhänger Aylisaftans sind, leider muss es hier gesagt werden, nicht selten fehlgeleitete Jünger Larjas, die, ohne es zu wissen, in ihrer Meinung zu extrem auf die Seite des Waldes gerückt sind. Die zweite Hauptgruppe, die ihm folgt sind zumeist verurteilte Triebtäter, da er diesen hilft, aus dem Kerker zu entkommen, wenn sie ihm dafür ihr Leben verpfänden. Doch egal, wer Aylisaftan folgt, eines haben alle gemein: Ihren Hass auf alle zivilisierten Völker und ihre Gefühlskälte, da ihnen ein Pakt mit diesem Widersacher sofort aller Gefühle beraubt und sie somit zu quasi Seelenlosen Anhängern seiner selbst macht.

=== Zeremonien/Rieten
Die meisten Anhänger Aylisaftans üben den Beruf des Jägers aus oder werden durch ihn zu einem selbigen gemacht. Es heißt, dass der Pakt den Paktierer zu einem absoluten Meisterschützen werden lässt. Der Hauptritus der „wilden Jäger“, wie die Anhänger im Volksmund genannt werden, ist es jedoch, niemals ein Tier zu verletzen, dem Gott jedoch den gehäuteten Leib eines jeden Menschen, Elfen, Halblings oder Zwerges zu opfern, den sie erlegen.

=== Aussehen
Die wilden Jäger tragen normale Jagdkleidung, jedoch hängen sie sich gerne Augen oder Ohren ihrer erlegten Opfer um den Hals und machen sich Leder aus deren Haut. Jedoch wie bei allen Paktierern gilt auch hier: Die Anhänger sind genauso listig, wie die göttlichen Gegenspieler und so würden sich viele nicht die Blöße geben, so herumzulaufen, dass sie jeder Laie sofort als das erkennt, was sie sind.

=== Aufgaben
Als ihre Hauptaufgabe sehen es diejenigen, die ihre Seele verkauft haben an, die Welt von allen zivilisierten Rassen zu bereinigen oder das Gleichgewicht anderweitig wieder herzustellen, so stehlen sie einem Jäger zum Beispiel seinen Bogen, kurz bevor er auszieht, einen Bären zu bekämpfen oder dem Krieger das Schwert, wenn er gegen Ratten und Fliegen in den Kampf zieht, welche die Menschen bedrohen. Hin und wieder ist es auch schon vorgekommen, dass sich ein Paktierer auf die Seite der Monster gestellt hat, um das Gleichgewicht wieder herzustellen.

=== Sonstiges
Wie die Anhänger eines jeden Erzdämonen können wilde Jäger niemals eine Stätte der Larja betreten. Ebenso spüren sie, wenn ein Geweihter in der Nähe ist, wie auch dieser ihre Anwesenheit spürt.

=== Bonus
-5% AP-Verbrauch bei Bewegung im Wald

=== Steigerungsstufen

[options="header"]
|=========================================================================
| Stufe | Vorraussetzung                            | Rang         | Bonus
| 1     | keine                                     | Gläubiger    | -5%  
| 2     | 10 Holz abliefern                         | Laie         | -5%  
| 3     | 10 Wolpertinger abliefern                 | Philosoph    | -5%  
| 4     | eine Holzhütte besitzen                   | Novize       | -5%  
| 5     | 1000 Harz abliefern                       | Kaplan       | -5%  
| 6     | ein Char muss 40 Wildnislebenskill haben  | Mönch        | -10% 
| 7     | ein Char muss 50 Wildnislebenskill haben  | Priester     | -15% 
| 8     | ein Char muss 60 Holzfällenskill haben    | Kardinal     | -20% 
| 9     | 5000 Wolpertinger abliefern               | Hohepriester | -25% 
| 10    | ein Char muss 100 Wildnislebenskill haben | Prophet      | -30% 
|=========================================================================
