:source-highlighter: highlight.js

== Bendur

Bendur ist als Gott des Meeres und der Winde bekannt. Er wird oft als dick und einen Vollbart tragend beschrieben. Eines seiner Lieblingstiere soll ein weißer Walfisch sein, den die Seeleute "Ljenerek" nennen.Entsprechend ist das Wappen Bendurs ein Weißer Wal auf blauem Grund.

=== Ordensgemeinschaft
In fast jedem Hafenort gibt es einen Priester. Novizen tragen rauchblaue Kutten. Bei Priestern sind diese Kutten weiß oder silbrig abgesteckt.

=== Aufgaben/Pflichten
Die wichtigsten Pflichten dieser Priester sind natürlich in ihrem Glauben begründet. Sie sorgen für die Einhaltung der Meeres- und Wasserordnung, was den Schutz der Wasserlebewesen und insbesondere die Problematik der Überfischung betrifft. Eine weitere wichtige Aufgabe ist die Erforschung der Meere und das damit verbundene Anlegen von Seekarten. Ebenso sind sie für symbolische Opferungen von Gold oder Edelsteinen zuständig, wenn die Menschen darum bitten, Bendur zu beschwichtigen bzw. seinen Segen zu erhalten. Dies ist besonders vor Seereisen der Fall. Daneben gibt es noch eine Einrichtung, welche als "Bendariat", als Priesterkommission, bekannt ist. Wenn ein Kapitän sein Schiff verloren hat, dann entscheidet dieses Gremium darüber, ob er evtl. Unterstützung für ein neues Schiff bekommt bzw. ob er überhaupt noch ein Schiff besitzen darf. Mit der Taufe eines Schiffes erteilen die Bendurpriester eine Schiffserlaubnis, ohne die ein Kapitän die Meere nicht befahren darf. Die Schiffstaufe ist auch ein beliebtes Spektakel. Um nämlich Kapitän eines Schiffes zu werden, muß dieser sein zukünftiges Schiff, was von erfahrenen Seeleuten ca. 1.5 Kilometer vom Ufer entfernt vor Anker gelassen wird, erschwimmen.

=== Sonstiges
Ein Brauch, der die Lebenslust Bendurs darstellt, ist das "Mannschaftsritual". Wenn eine Mannschaft ein Jahr lang zusammen auf See war, so wird ein Faß Bier in die Gischt geworfen, welches die Mannschaft nur mit Hilfe eines Kleinbootes bergen darf. Danach wird die Mannschaft gesegnet und darf sich mit den Namen des Schiffes Schmücken - sie ist jetzt eine Familie.Es wird gefeiert.Jeder Seemann trägt einen sogenannten Bendurtaler am Ohr oder um den Hals, um sich ordentlich bestatten zu lassen. Dies ist notwendig, da immer wieder Schiffe mitsamt ihrer Mannschaft untergehen. Man erzählt sich, daß diejenigen, die angeschwemmte Tote plündern, nie wieder ruhig schlafen können. 


=== Gegend#mon
Margintanor