:source-highlighter: highlight.js
== Fedimalan

Fedimalan, Herr der Siechen, wie er genannt wird, ist ein Bringer von Leid. Wo er ist, ist der Tod auf dem Land und hält grausame Ernte. Seuchen, Krankheiten, Hungersnöte, Streitigkeiten sind die Werke dieses letzten bekannten Dämon. Er lässt Pflanzen noch in der Saat vergehen und Vorräte, die den ganzen Winter halten sollten, verfaulen. Dargestellt wird er als alter Medicus, dessen linke Hand ein Operationsbesteck hält und dessen Rechte von etlichen Beulen und Warzen verzehrt ist. Er trägt in jeder Darstellung eine Schnabelmaske, das Zeichen der Seuche. 

=== Anhänger
Welcher verzerrte Geist diesem Gegenspieler freiwillig folgt, ist noch schleierhaft, denn bis zum heutigen Tag ist kein einziger Paktierer jemals gesichtet oder verhaftet worden. 

=== Zeremonien/Rieten
Weitestgehend unbekannt. Die Bücher der heiligen sieben berichten in Caput VII, Zeile 4-72 von einem Ritual, bei dem Wendaria geschändet werden soll, indem ihre Ähren zu seinem unheiligen Zeichen, welches drei längs und zwei diagonal Linien ähnelt, gelegt und dann verbrannt werden. Daraufhin brechen Hunger und Siechtum über das Land herein. Bis jetzt wurde ein solches Zeichen allerdings nur in den Zeiten der Avalonseuche gefunden, und dort konnte kein Zusammenhang zwischen Seuche und Fedimalans Einwirken festgestellt werden. 

=== Aussehen
Unbekannt. 

=== Aufgaben
Es wird vermutet, dass die Anhänger, sollte es sie geben, die Aufgabe haben, Seuchen unter das Volk zu bringen und es so zu schwächen, in Glaube und Lebenskraft.

=== Sonstiges
Dieser Irrglaube ist noch weitestgehend unerforscht. 

=== Bonus
20% besseres Rasten