:source-highlighter: highlight.js
== Larja

Larja wird als Göttin der Jagd, des Wildes und der Sümpfe geehrt. In Bildern wird sie als rothaarige Frau, die auf einem Hirsch sitzt und einen Bogen trägt, dargestellt.

=== Ordensgemeinschaft
Es gibt nur im Tempel Priester. Sie sind wie Waldläufer gekleidet. Ansonsten gibt es noch "Die Trägerschaft der Grünen Bande", welche außerhalb des Tempels auf die Einhaltung von Larja’s Gesetzen achten.

=== Aufgaben/Pflichten
Im Wesentlichen ist im Sinne Larja’s darauf zu Achten, das alle Tiere vor sinnloser Vernichtung bewahrt werden, keine Art ausgerottet wird und keine Tierkinder sowie Muttertiere getötet werden. Dies versuchen die Priester und "Die Trägerschaft der Grünen Bande" in die Tat umzusetzen. Zu diesem Zweck bringen sie z.B. viele Gerüchte über Gefahren und Ungeheuer, die sich in Wäldern und Sümpfen herumtreiben sollen, in Umlauf. Da Larja auch als Hüterin so mancher Heimlichkeiten bekannt ist, haben solche Maßnahmen auch den Zweck, Geheimnisse vor den Menschen zu bewahren.

=== Sonstiges
Da es keine flächendeckende Priesterschaft für diese Göttin gibt, werden symbolisch Opfer dargebracht. Aus diesem Grunde werden z.B. vor dem Eintritt in einen Wald, kleine Altäre aufgebaut, auf denen ein paar Gaben, normalerweise Obst und Gemüse, aufgebahrt werden. Spezielle Berufsgruppen wie Jäger, Naturheiler und Kräuterfrauen, besitzen oft Larja geweihte Gegenstände, mit denen sie ihre rituellen Opferungen durchführen. Dies können Messer, Schalen oder Holzschreine sein. 

=== Gegendämon
Aylisaftan

=== Bonus
-5% AP-Verbrauch bei Bewegung im Wald.