:source-highlighter: highlight.js
== Lismagafan

Lismagafan verkörpert all das, was sich Plünderer wünschen. Er liebt es, seinen Gegnern die eigene Stärke zu demonstrieren, Unschuldige zu töten, Frauen und Kinder zu schänden. Ehrenwerter Zweikampf und Gerechtigkeit ist ihm zuwider. Brandschatzen und Mordbrennen, das ist seine wahre Freude. Würden er und Urvan sich irgendwann duellieren und Urvan würde ihn zum fairen Zweikampf fordern, so müsste er damit rechnen, dass ihm einer von Lismagafans Schergen einen Dolch in den Rücken schiebt, sobald sich das Glück gegen seinen Herren wendet. Lismagafans Zeichen ist der brennende Pfeil, dargestellt wird er als schlanker, athletisch gebauter, junger Kämpfer in geschwärzter Rüstung und mit einem Zweihänder in der einen und einer Rauchkugel in der anderen Hand.

=== Anhänger
Die Anhängerschaft des Lismagafan ist wahrscheinlich die größte unter allen Dämonen. Viele Söldner kämpfen in seinen Reihen, da er ihnen verspricht, sie niemals in einem Kampf unterliegen zu lassen. Rache und Hass spornen ihn an, so demütigt er seine Anhänger permanent, und doch steht auf jeden erfolgreichen Kampf - was in Lismagafans Augen sehr weit auszulegen ist - eine saftige Belohnung. Neben den Söldnern finden sich auch Gesetzlosen, Plünderer, Mörder und Folterknechte in seinen Reihen. Jeder Anhänger neigt zu Jähzorn, Implusivität und Vorurteilen. 


=== Zeremonien/Rieten
Es gibt nur zwei Riten, die beinahe jeder der Fehlgeleiteten unter Lismagafan ausübt: Das sprichwörtliche Blutsaufen. Vor einer Schlacht trinkt ein Anhänger das Blut eines starken Tieres, um dessen Kräfte zu verinnerlichen, nach einer Schlacht trinkt er das Blut seines stärksten oder schwächsten Gegners, dass darf er selbst wählen.


=== Aussehen
Das eindeutigste Merkmal des Lismagafan Paktierers ist die geschwärzte Brünne, die ein jeder der ihren trägt. Sollte jemand mit einer solchen Brünne gesichtet werden, ist dies sofort an den zuständigen Urvantempel zu melden! 


=== Aufgaben
Die Aufgaben sind einfach gesagt: Morden, Brandschatzen, Plündern, Frauen und Kinder schänden. 

=== Bonus
5% mehr kritische Treffer

=== Steigerungsstufen

[options="header"]
|====================================================================
| Stufe | Vorraussetzung                       | Rang         | Bonus
| 1     | keine                                | Gläubiger    | 5%   
| 2     | ein Char muss 10 Nahkampfskill haben | Laie         | 5%   
| 3     | 200 Kampfruhm                        | Philosoph    | 5%   
| 4     | 250 Waffen abliefern                 | Novize       | 5%   
| 5     | 7500 Kampfruhm                       | Kaplan       | 5%   
| 6     | ein Char muss 40 Nahkampfskill haben | Mönch        | 10%  
| 7     | 25.000 Kampfruhm                     | Priester     | 15%  
| 8     | ein Char muss 60 Nahkampfskill haben | Kardinal     | 20%  
| 9     | ein Char muss 75 Nahkampfskill haben | Hohepriester | 25%  
| 10    | 1 Untotenfürst töten                 | Prophet      | 30%  
|====================================================================
