:source-highlighter: highlight.js
== Maki

Maki ist der Gott der Handwerker, der Händler und der zwielichtigen Gestalten. Wegen letzterer gilt Maki auch als Hüter längst als verschollen geglaubter Gegenstände. Oft wird er als klein und mit langer Nase abgebildet; teilweise auch als Wiesel.

=== Ordensgemeinschaft
Priester tragen gelb-braune Kutten.

=== Aufgaben/Pflichten
Priesterlichen Aufgaben sind die Freihaltung der Handelsrouten, die Belebung des Handels, die Förderung von Ideen- und Technikaustausch in der Handwerkskunst und ebenso die Förderung der allgemeinen Künste (Musik-, Mal-, Schauspiel- und Schreibkunst). Aber auch die zwielichtigen Künste wie Diebstahl bitten um Maki’s Beistand. Wie dieser gestaltet ist, dies ist nicht bekannt und die Priester schweigen sich beharrlich darüber aus - sie leugnen diese Tatsache sogar.Vor allem wegen der sogenannten „Ausgleichsspeisung“, einer Speisung der Armen, ist Maki, trotz seiner angeblichen Unterstützung des undurchsichtigen Gesindels, ein sehr geachteter Gott.

=== Sonstiges
Jeder Handwerker und Händler, aber auch Künstler, spendet freiwillig. Da es nur zwei Tempel gibt, so gehen Priester auf Wanderschaft, diese Spenden in Empfang zu nehmen. Mindestens einmal im Leben, müssen Handwerker, Händler und Künstler, zu einer Pilgerfahrt zu einem Makitempel aufbrechen. Dort erhalten sie eine geweihte Münze, die in der Mitte ein Loch mit einem schwarzen Ring hat und auf deren eine Hälfte ein Hammer, auf der anderen eine Feder eingraviert ist. 


=== Gegendämon
Sulganoth