:source-highlighter: highlight.js
== Margintanor

Margintanor wird häufigst als alter Kapitän mit Hakenhand und/oder Holzbein dargestellt, sollten denn mal Aufzeichnungen über diesen göttlichen Gegenspieler gefunden werden. Ihm werden die Stürme, auf See wie auf Land zugeschrieben, die ganze Ernten vernichten, einfache Fischerboote ins Unglück stürzen und sogar kleine Inseln im Meer versinken lassen. Ihn fürchten Entdecker und Schiffsleute, die sich aufgemacht haben, neue Länder zu erkunden. Denen, die angeschwemmte Tote bestehlen, schickt Margintanor auf ewig übelste Alpträume, in denen sie die Rolle des Toten übernehmen und seine letzen Minuten miterleben. Diese Träume sollen so realistisch sein, dass schon manch einer einen Seelenheiler besuchen musste, oder gar schlimmeres.

Anhängerschaft: Wenn auch wenige, so haben sich doch ein paar düstere Wesenheit mit ihrem Leben dem Dämon Margintanor verschrieben, da er ihnen verspricht, auf immer glücklichen Fang zu haben, eine Reise auf jeden Fall günstig zu meistern, oder gar vollbeladene Frachtschiffe nach einem Seegefecht zu erbeuten. Es wird ihnen nachgesagt, sie könnten Marginantors Wappentiere, die Krake, herbeirufen, die alle armen Hunde, die während einer Schlacht in die Fluten fallen sofort zerfetzen und in Marginantors Reich zerren.

Zeremonien/Rieten: Zeremonien sind nicht bekannt, als Ritus gilt das Opfern von Meerestieren, die im allgemeinen als schön, anmutig oder intelligent empfunden werden, wie z.B. Delphine. Die höchsten Opfergaben, die ihm jedoch entgegen gebracht werden können, sind Wale, da diese bekanntermaßen die Wappentiere Bendurs ist, ein brennendes Schiff, welches gerade geplündert wurde oder einer der Geweihten des Gottes.

Aussehen: Leider kann jedes Wesen ein Paktierer sein, da sie keine feste Gewandung tragen, sondern zumeist aussehen, wie normale Seeleute.

Aufgaben: Jeder Paktierer Margintanors hat die Aufgabe, Schiffsreisen ins Unglück zu stürzen, und dies auf subtile Art und Weise, wie z.B. das Fälschen von Seekarten oder das Schütten von Salz in die Trinkwasservorräte. Werden diese Aufgaben zur Zufriedenheit des Gegenspielers erfüllt, so sollen die Anhänger angeblich immer wieder gesund an ihren Heimathafen angekommen sein.

Sonstiges: Anhänger dieses Dämons können keine Tempel des Bendur betreten oder seinen Segen erhalten. Es schreckt sie ab, und quält sie, mit dem Gott in Kontakt zu treten. 