:source-highlighter: highlight.js
== Muradjanian

Muradjanian ist die Herrin des dunklen Wissens.Ihr Ziel ist es, jedem Lebewesen alles Wissen dieser Welt zu geben. Nichts soll verborgen bleiben, kein Geheimnis unausgesprochen. Das kein Wesen jemals damit fertig werden würde, ist ihr durchaus bewusst. Diejenigen, die ihr folgen sind zumeist verblendet, von der vermeintlichen Macht, alles zu wissen. 

Muradjanian wurde bis jetzt nur ein einziges Mal und da in der Gestalt einer jungen Frau in einem Magiegewand, welches die Tiefe des Sternenhimmels widerspiegelte, gesichtet, was in ungefähr den Zeichnungen der heiligen Schriften entspricht. Sie besitzt kein Wappentier, sondern nur den Achtfach- oder - Chaosstern als Symbol.

=== Anhänger
Diejenigen, die sich der Allwissenden anschließen, sind nach Abschluss des Paktes nicht mehr als ein paar sabbernde, schreiende Irre, da sie es nicht ertragen können, alles auf der Welt zu wissen, und die Vergangenheit, die Gegenwart und die mögliche Zukunft zu kennen. Und doch folgen einige Individuen diesem verzerrten Weg, vor allem Schwarzmagier, die Machthungrig sind, sind ihm zugeneigt. Und hin und wieder gibt es auch einen Geist, der all diesem Wissen standhalten und es ertragen kann. Dies passiert gar selten, noch seltener, als es passiert, dass jemand einen Pakt mit der Herrin der Zeit, wie sie auch genannt wird, eingeht, doch sollte es passieren, so hat jeder Magier und Geweihte des Pheron einen unheimlich mächtigen Gegner vor sich. Es ist nur ein belegter Fall eines solchen Paktierers bekannt, dieser ist in Pherons Überlieferungen, 2. Band, viertes Kapitel, Zeilen 6-34 nachzulesen. 

=== Zeremonien/Riten
Sind weitestgehend unbekannt, aus dem Grund, dass die Anhänger nicht in der Lage waren, befragt zu werden und es noch kein Geweihter überlebt hat, einen „Scheinpakt“ einzugehen. Ansonsten ist es nur belegt, dass hin und wieder Bibliotheken und Magierakademien einem Brand unterlagen, welches vielleicht auf die Diener der Dämonin zurückzuführen ist. 

=== Aussehen
Zumeist tragen die Diener nach ihrer Paktschließung bis zum Ende ihres Lebens die selben Gewänder, wie vor dem Pakt, somit ist nicht auszuschließen, dass ein Magier, dessen Kleidung allzu verjährt aussieht, ein Anhänger der Muradjanian sein mag. Zudem wurde beobachtet, dass diese Leute niemals einen Bart tragen und hin und wieder ihr Haupthaar abschneiden. 

=== Aufgaben
Diejenigen, die das Wissen vertragen, welches ihnen zu Teil wird, setzen ihr Leben zumeist als Berater hoher Persönlichkeiten fort, denen sie böse Ratschläge mit ihrem Wissen geben, welche ganze Völker in den Abgrund stürzen können. Alle anderen führen niedere Aufgaben aus, wie z.B. die oben genannten Brände zu legen. Hierbei sind sie so fanatisch, dass sie nichts außer Turas Hand stoppen kann... oder Muradjanian selbst.  

=== Bonus
10% verbesserte Spruchchance auf Gebäudezauber, Gruppen- und Heldenverzauberungen und Beschwörungen

=== Steigerungsstufen

[options="header"]
|======================================================================
| Stufe | Vorraussetzung                         | Rang         | Bonus
| 1     | keine                                  | Gläubiger    | 10%  
| 2     | 1 Buch abliefern                       | Laie         | 10%  
| 3     | ein Char muss 20 Magiekundeskill haben | Philosoph    | 10%  
| 4     | 100 Thaum abliefern                    | Novize       | 10%  
| 5     | ein Rezept besitzen                    | Kaplan       | 10%  
| 6     | ein Char muss 40 Magiekundeskill haben | Mönch        | 20%  
| 7     | 5 Rezepte besitzen                     | Priester     | 30%  
| 8     | ein Char muss 60 Magiekundeskill haben | Kardinal     | 40%  
| 9     | 5000 Bücher abliefern                  | Hohepriester | 50%  
| 10    | ein Char muss 100 Magiekundekill haben | Prophet      | 60%  
|======================================================================
