:source-highlighter: highlight.js
== Olimanir

Olimanir ist die Herrin über die Toten, die nicht begraben und gesegnet werden konnten. Ihre Geschöpfe sind die Untoten und die Skelette, und genau diese okkulte Macht bringt viele dazu, sich ihr anzuschließen. Wo auch immer ein Toter nicht durch einen Turapriester gesegnet und gesalbt wurde, kann es sein, dass er wieder aufersteht um dem Willen der „einzig wahren“ zu folgen. Ihr Zeichen ist die Krähe und wird als Schwester der Tura dargestellt, bis auf die Tatsache, dass ihre Haut ebenholzschwarz ist und ihre Augen blutrot.

=== Anhänger
Anhänger der Olimanir haben viele Gründe, zu ihr zu kommen. Ewiges Leben, die Wiederauferstehung eines Geliebten Menschen oder einfache Macht über das Totenreich sind nur wenige von ihnen. All dies verspricht die Herrin Olimanir, doch wenn der Pakt ausläuft, wird der Paktierer dazu verdammt, auf ewig in seinem verrotenden Körper als Geschöpf Olimanirs über die Scherbe zu wandeln. 

=== Zeremonien/Rieten
Traditionelle Zeremonien Olimanirs sind immer wieder zu beobachten: Grabraub, Schändung von Friedhöfen und leider auch hin und wieder von Leichen. 

=== Aussehen
Ein bestimmtes Aussehen haben die Paktierer nicht, aber eine Aura der Kälte umgibt sie, die jeder intuitiv spürt, der sich in der Nähe eines Paktierers aufhält und nicht selbst ein Paktierer ist. Geweihte bekommen ein schlechtes Gefühl, wenn ein Paktierer in ihrer Nähe ist, Turapriester wissen, dass ein Paktierer unter ihnen ist. Dazu kommt ein leicht süßlicher Geruch, der von den Paktierern ausgeht. Dieser wird mit fortschreitendem Alter immer stärker, bis er schließlich zu wahrem Leichengeruch ausartet. 

=== Aufgaben
Was die wahren Ziele Olimanirs und ihrer Paktierer ist, wissen wohl nur sie selbst, was jedoch immer wieder beobachtet wurde ist, dass Leichen zur Übergabe an die Dämonin bereit gemacht wurden. Sonstiges: Turaacker sind für diese Paktierer ohne Probleme begehbar, auch wenn sie der Herrin gesegnet sind. 
  
Olimanir...Kalt ist der Krähe eisernes Herz(auf den Eisinseln, da sind auch viele Untote!)

=== Bonus
15% verbesserte Heilung

