:source-highlighter: highlight.js
== Pheron

Pheron, der Gott des Wissens, der Weisheit und der Wissenschaft, wird oft als alter, weißhaariger Gelehrter dargestellt, der eine weiße Robe mit zurückgeschlagener Kapuze trägt sowie Buch und Feder hält. Es gibt aber auch Darstellungen, in denen eine weiße Eule mit silbrigem Halbmond auf gräulichem Grund symbolisch für Pheron abgebildet ist.

=== Ordensgemeinschaft
Die Priester Pherons sind an ihren weißen Kutten zu erkennen. Sie leben entweder in einem Tempel, welche Bibliotheken ähneln, oder aber in abgelegenen Gegenden, um ihren Studien ungestört nachgehen zu können.

=== Aufgaben/Pflichten
Zu den Pflichten eines Priesters gehört die Mehrung, Vermittlung sowie die Anwendung von Wissen.

=== Sonstiges
Weil die Pheronpriester als weise und klug gelten, werden sie bevorzugt von Adligen als Berater eingesetzt. Manchmal werden sie auch gebeten, Recht zu sprechen, vor allem, wenn das Forschungsgebiet eines Priesters, die Rechtswissenschaft ist.Verbindung zu Magiern: Einst lehnte der größte Teil der Pheronpriester Magie und ihre Anwender ab. Als dunkle Beschwörer, die ihre eigenen Grenzen nicht kennen, waren sie verschrien. Mittlerweile hat sich jedoch gezeigt, das Magiertürme und ihre Laboratorien genauso effektive Forschungszentren zur Mehrung des Wissens repräsentieren, wie Universitäten und Bibliotheken. Schon lange sind die stetig forschenden Magier aus der Glaubensgemeinschaft der Pheronis nicht mehr wegzudenken. Noch immer ist aber von Geheimbünden innerhalb des Pheronkonvents die Rede, die ihren Wissensdrang über das Leben Unschuldiger stellen. 

=== Gegendämon
Muradjanian

=== Bonus
10% verbesserte Spruchchance auf Gebäudezauber, Gruppen- und Heldenverzauberungen und Beschwörungen.