:source-highlighter: highlight.js
== Sulganoth

Sulganoth steht somit für Gier, Hinterlist, Tücke, Intrigen und Unglück, jedoch auch für schwarzen Humor, der keineswegs als verwerflich gilt. Er zerstört Existenzgrundlagen, bringt den Tod durch ein Attentat, lässt Ersparnis und Erbe verschwinden, nur um dann irgendwann in einem stillen Moment aufzutauchen und zu sagen „Du willst dies alles wiederhaben? Dann folge mir. Ich will dir Dinge zeigen, so schön, wie du es dir nicht erträumen kannst...“. Die armen Seelen, die auf dieses Angebot eingehen werden zunächst reich beschenkt, jedoch dann müssen sie all die verwerflichen Dinge tun, die Sulganoth reizen. Noch dazu kann Sulganoth so gut Handeln, als wäre er Maki persönlich und so fällt ein Vertrag mit ihm immer zu seinen Gunsten aus. Sein Wappentier ist die Schlange und zumeist wird er als dunkle Gestalt dargestellt, die einen menschlichen Körperbau besitzt, ihr Gesicht jedoch unter einer Kapuze versteckt und einen goldenen Dolch in den Händen hält. 

=== Anhängerschaft
Die Anhängerschaft setzt sich aus allen sozialen Schichten zusammen: Reiche Handelsherren ebenso wie kleine Diebe oder Mörder. Alle, die nur nach Macht und Reichtum streben sind schon einen Schritt näher bei ihm. Zumeist sind die Anhänger von einer Droge oder einem anderen Suchtmittel abhängig, da dies Teil des Bundes ist. Zeremonien/Rieten: Sulganoth-Paktierer sind stets geizig und würden sogar einem Blinden die Münzen aus seiner Schale klauen, wenn sich die Gelegenheit bieten würde. Alles, was gegen das Gesetz ist, ist Ritus der Anhänger, vor allen Dingen Diebstahl, Raub und Mord. Darüber schmieden einige von ihnen Trickwaffen oder Vorrichtungen, die der Benutzung selbiger dienen, wie zum Beispiel Armschienen, in welche ein Dolch eingeführt werden kann, welcher dann auf eine bestimmte Drehung des Armes hin hervorschießt. 

=== Aussehen
Die meisten Paktierer hüllen sich in dunkle oder schwarze Tücher, deren Innenseite rot ist, Kapuzenumhänge sind zum Teil sehr beliebt. Jeder Anhänger hat ein Medaillon dabei, welches aus einem speziellen Metall, dem so genannten Schwarzsilber hergestellt wurde. Wo er es trägt ist jedoch ungewiss.

=== Aufgaben
Die Aufgabe eines jeden Anhängers ist es, zu verführen und allem zu gehorchen, was Sulganoth aufträgt, dazu gehört der Mord an Geweihten oder reichen Bürgern, der Kampf gegen das Adelssystem und ähnliche Dinge. 

=== Bonus
-10% AP-Verbrauch beim Verstecken