:source-highlighter: highlight.js
== Tura

Tura, die Schöne, welche als sehr blasse und schlanke Frau, welche mit Eleganz völlig in Schwarz gekleidet ist, beschrieben wird, gilt als Herrscherin über das Reich der Toten. Der graue Delphin „Griel“, der die Toten ins Totenreich bringt, wird oft als Symbol verwendet.

=== Ordensgemeinschaft
Die schweigsamen Priester tragen schlichte, schwarze Kutten. Diejenigen, die Bestattungen durchführen dürfen, tragen eine Medaille, auf der sich das Abbild eines Delphins befindet. Bei einer Bestattung tragen sie schwarzen Kutten, deren Ränder silbern abgesteckt sind. Oftmals ist aber auf einem Turaacker nur ein Priester tätig, der zu Bestattungen befugt ist. Viele erzählen sich, daß diese Priester die andere Seite, das Totenreich, gesehen hätten, worauf die Schweigsamkeit dieser Priester zurückzuführen wäre.

=== Aufgaben/Pflichten
In erster Linie sind die Priester für die ordnungsgemäße Bestattung von Toten da. Sie sind die einzigen, die Leichen untersuchen dürfen, weshalb sie auch als Hüter der Totengeheimnisse bekannt sind und darum oftmals einige Kenntnisse über die Heilkunde haben.

Weiterhin achten sie darauf, daß die Toten geehrt werden. Dies trifft besonders auf die „Mol-Tage“ zu. Sie greifen aber auch ein, wenn die Ruhe der Toten gestört wird oder aber, wenn Seelen nicht zur Ruhe kommen.

=== Sonstiges
Jeder spendet freiwillig dem zuständigen Turapriester. 

=== Gegendämon
Olimanir