:source-highlighter: highlight.js
== Urvan

Urvan ist der Gott des Kampfes und des Gesetzes, weswegen er durch ein Schwert, das in eine Wage eingearbeitet ist, symbolisiert wird. Die graue Farbe des Hintergrundes steht als Zeichen für Neutralität.


=== Organisation
Es wird in Priester und Urvaner unterschieden. Priester sind an ihren hellgrauen Kutten zu erkennen. Die Urvaner sind die Kämpfer ihres Ordens. Sie tragen meist einen hellgrauen Mantel und einen grauen Schild, wo jeweils ein Schwert abgebildet ist.


=== Aufgaben/Pflichten
Die Hauptmotive für Priester und Urvaner sind, Vorbild zu sein und jedwede Feinde zu bekämpfen. Die Priester werden dementsprechend oftmals zu Richtern ernannt, wo sie mit der Durchsetzung bestehender Gesetze beauftragt sind.

Besonders problematisch ist, wenn es zu Spannungen zwischen verschiedenen Gesetzen kommt, was z.B. der Fall ist, wenn ein Sklave in eine Grafschaft flieht, in der Sklaverei verboten ist. Daß dabei manchmal Urvaner gegen Urvaner kämpfen, legen die Priester als ehrenhafte und vorbildliche Loyalität dem Gesetzgeber gegenüber aus.
Gelegentlich geraten sie auch in Konflikte mit Pheronpriestern, die bei Streitigkeiten ebenfalls oft um Rat gefragt werden, wobei diese Entscheidungen nicht selten auf Erfahrungswerten bzw. Logik, anstatt auf geltendem Gesetz, beruhen. Bei Wettkämpfen, aber auch bei Zweikämpfen, die Klarheit über Recht und Unrecht erbringen sollen, wirken die Priester als Schiedsrichter, wo sie dem Leitgedanken eines fairen Kampfes Rechnung tragen. Entsprechend diesem Gedanken, verachten die Urvaner Fernwaffen und andere Hilfsmittel in einem ehrenhaften Duell.
Für die Verteidigung des Glaubens sind die Urvaner zuständig. So sind sie es, die in und um den Tempel der Einigkeit patrouillieren. Weil auch sie Vorbild sein wollen, ziehen Urvaner oft aus, um große Taten zu vollbringen. 