:source-highlighter: highlight.js
== Wendaria

Wendaria, die Göttin der Fruchtbarkeit, und der Gesundheit, wird sehr oft als wohlbeleibte, rosig, stets lachende und fröhliche Frau, deren mütterliche Strenge aber noch zu erahnen ist, dargestellt. Symbolisiert wird sie aber auch durch ein Ähre und einer Schale bzw. einer Ähre und Wasser.

Organisation: In vielen Ortschaften sind Priester und Priesterinnen tätig. Ähnlich den Turapriestern, kann es passieren, daß sie für mehrere Ortschaften zuständig sind. Neben den Priestern gibt es noch die Wendariaten, welche die Ordenskrieger der Wendaria sind. Sie sind einzig und allein dazu da, um den Heimattempel zu verteidigen.

Aufgaben/Pflichten: Zu den Pflichten der Priester gehört, keine Verletzten oder Kranken abzuweisen. Es ist ihre Aufgabe, ihnen zu helfen. Des Weiteren führen sie die Taufe von Kindern durch.
Wendaria um eine gute Ernte, Kindersegen etc. zu bitten bzw. sich dafür zu bedanken, ist weiterhin eine der wichtigsten Aufgaben der Priester.

Sonstiges: Jeder Mensch spendet freiwillig dem jeweils zuständigen Priester bzw. der jeweiliges zuständigen Priesterin. 

=== Gegendämon
Fedimalan

=== Bonus
20% besseres Rasten

=== Steigerungsstufen

[options="header"]
|=======================================================================
| Stufe | Vorraussetzung                          | Rang         | Bonus
| 1     | keine                                   | Gläubiger    | 20%  
| 2     | 1 Pilz abliefern                        | Laie         | 20%  
| 3     | ein Char muss 20 Heilenskill haben      | Philosoph    | 20%  
| 4     | Bauernhof besitzen                      | Novize       | 20%  
| 5     | ein Char muss 35 Heilenskill haben      | Kaplan       | 20%  
| 6     | 1000 Lebertran abliefern                | Mönch        | 40%  
| 7     | Gasthaus mit 10 Zimmerqualität besitzen | Priester     | 60%  
| 8     | ein Char muss 60 Heilenskill haben      | Kardinal     | 80%  
| 9     | 5000 Kakao abliefern                    | Hohepriester | 100% 
| 10    | ein Char muss 100 Heilenskill haben     | Prophet      | 120% 
|=======================================================================
