_This article is about the event known as the Cataclysm. For the expansion, see [World of Warcraft: Cataclysm](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Cataclysm "World of Warcraft: Cataclysm")._

[![](https://static.wikia.nocookie.net/wowpedia/images/d/dc/Cataclysm_Art_John_Polidora.jpg/revision/latest/scale-to-width-down/230?cb=20110608081750)](https://static.wikia.nocookie.net/wowpedia/images/d/dc/Cataclysm_Art_John_Polidora.jpg/revision/latest?cb=20110608081750)

A landscape ravaged by the Cataclysm.

[![](https://static.wikia.nocookie.net/wowpedia/images/2/2f/Temple-of-Earth-World-Pillar.jpg/revision/latest/scale-to-width-down/180?cb=20170715143149)](https://static.wikia.nocookie.net/wowpedia/images/2/2f/Temple-of-Earth-World-Pillar.jpg/revision/latest?cb=20170715143149)

The damaged [World Pillar](https://wowpedia.fandom.com/wiki/World_Pillar "World Pillar") in [Deepholm](https://wowpedia.fandom.com/wiki/Deepholm "Deepholm").

The **Cataclysm**<sup id="cite_ref-1"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-1">[1]</a></sup><sup id="cite_ref-2"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-2">[2]</a></sup> (also called the **Great Cataclysm**,<sup id="cite_ref-3"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-3">[3]</a></sup> the **great upheaval**,<sup id="cite_ref-4"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-4">[4]</a></sup><sup id="cite_ref-5"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-5">[5]</a></sup><sup id="cite_ref-6"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-6">[6]</a></sup> or the **Shattering**)<sup id="cite_ref-7"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-7">[7]</a></sup><sup id="cite_ref-8"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-8">[8]</a></sup><sup id="cite_ref-9"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-9">[9]</a></sup> was a chain reaction of natural disasters that struck [Azeroth](https://wowpedia.fandom.com/wiki/Azeroth "Azeroth") following [Deathwing](https://wowpedia.fandom.com/wiki/Deathwing "Deathwing") blasting his way from [Deepholm](https://wowpedia.fandom.com/wiki/Deepholm "Deepholm") into the world, breaking down the boundaries between the [Elemental Plane](https://wowpedia.fandom.com/wiki/Elemental_Plane "Elemental Plane") and the physical world.<sup id="cite_ref-Chronicle3_199_10-0"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-Chronicle3_199-10">[10]</a></sup> The damage caused to the [World Pillar](https://wowpedia.fandom.com/wiki/World_Pillar "World Pillar") caused the Elemental Plane to collide with the physical realm,<sup id="cite_ref-11"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-11">[11]</a></sup> resulting in drastic geographical upheaval, causing chaotic [elementals](https://wowpedia.fandom.com/wiki/Elemental "Elemental") to pour out into the world of Azeroth. Earthquakes, volcano eruptions and floods followed in his wake, killing thousands<sup id="cite_ref-Chronicle3_199_10-1"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-Chronicle3_199-10">[10]</a></sup> and reshaping the face of the world.

It is also the era in which the stories of _[Cataclysm](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Cataclysm "World of Warcraft: Cataclysm")_ took place<sup id="cite_ref-12"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-12">[12]</a></sup> and ended with the demise of [Deathwing](https://wowpedia.fandom.com/wiki/Deathwing "Deathwing").<sup id="cite_ref-13"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-13">[13]</a></sup>

## Precursor

<table><tbody><tr><td><a href="https://static.wikia.nocookie.net/wowpedia/images/f/fe/Stub.png/revision/latest?cb=20101107135721"><img alt="" src="https://static.wikia.nocookie.net/wowpedia/images/f/fe/Stub.png/revision/latest/scale-to-width-down/17?cb=20101107135721" decoding="async" loading="lazy" width="17" height="20" data-image-name="Stub.png" data-image-key="Stub.png" data-src="https://static.wikia.nocookie.net/wowpedia/images/f/fe/Stub.png/revision/latest/scale-to-width-down/17?cb=20101107135721"></a></td><td>This section is <b>a <a href="https://wowpedia.fandom.com/wiki/Lore" title="Lore">lore</a> stub</b>.</td></tr></tbody></table>

After the [war against the Lich King](https://wowpedia.fandom.com/wiki/War_against_the_Lich_King "War against the Lich King"), [War Against the Nightmare](https://wowpedia.fandom.com/wiki/War_Against_the_Nightmare "War Against the Nightmare") and the uprising of the shamanistic [Earthen Ring](https://wowpedia.fandom.com/wiki/Earthen_Ring "Earthen Ring"), the world of Azeroth was threatened by the [Elemental Unrest](https://wowpedia.fandom.com/wiki/Elemental_Unrest "Elemental Unrest").

The unrest also caused a ship carrying some [Bloodsail Buccaneers](https://wowpedia.fandom.com/wiki/Bloodsail_Buccaneers "Bloodsail Buccaneers") to take shelter near a patch of tiny islands as the seas heaved to and fro. After the initial elemental unrest passed, their leader, [Admiral Eliza Goreblade](https://wowpedia.fandom.com/wiki/Dread_Admiral_Eliza "Dread Admiral Eliza"), found a hidden pirate treasure of the _[Bellwether](https://wowpedia.fandom.com/wiki/Bellwether "Bellwether")_ ship containing two [Legion](https://wowpedia.fandom.com/wiki/Burning_Legion "Burning Legion") cutlasses, [Fate](https://wowpedia.fandom.com/wiki/Fate "Fate") and [Fortune](https://wowpedia.fandom.com/wiki/Fortune "Fortune").<sup id="cite_ref-14"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-14">[14]</a></sup>

## Consequences

<table><tbody><tr><td><a href="https://static.wikia.nocookie.net/wowpedia/images/f/fe/Stub.png/revision/latest?cb=20101107135721"><img alt="" src="https://static.wikia.nocookie.net/wowpedia/images/f/fe/Stub.png/revision/latest/scale-to-width-down/17?cb=20101107135721" decoding="async" loading="lazy" width="17" height="20" data-image-name="Stub.png" data-image-key="Stub.png" data-src="https://static.wikia.nocookie.net/wowpedia/images/f/fe/Stub.png/revision/latest/scale-to-width-down/17?cb=20101107135721"></a></td><td>This section is <b>a <a href="https://wowpedia.fandom.com/wiki/Lore" title="Lore">lore</a> stub</b>.</td></tr></tbody></table>

[![](https://static.wikia.nocookie.net/wowpedia/images/d/d0/Barrens_divided.jpg/revision/latest/scale-to-width-down/180?cb=20110423015702)](https://static.wikia.nocookie.net/wowpedia/images/d/d0/Barrens_divided.jpg/revision/latest?cb=20110423015702)

The [Great Divide](https://wowpedia.fandom.com/wiki/Great_Divide "Great Divide"), one of many fissures in the land caused by the Cataclysm.

_Main article: [Patch 4.0.3a (world changes)](https://wowpedia.fandom.com/wiki/Patch_4.0.3a_(world_changes) "Patch 4.0.3a (world changes)")_

The coastlines of [Kalimdor](https://wowpedia.fandom.com/wiki/Kalimdor "Kalimdor") and the [Eastern Kingdoms](https://wowpedia.fandom.com/wiki/Eastern_Kingdoms "Eastern Kingdoms") shifted, flooding some old lands and exposing new ones. Whole parts of the world, like [Thousand Needles](https://wowpedia.fandom.com/wiki/Thousand_Needles "Thousand Needles") and a large chunk of [Tanaris](https://wowpedia.fandom.com/wiki/Tanaris "Tanaris"), ended up underwater. In some cases, tidal waves caused by the Cataclysm flooded or destroyed coastal settlements like [Auberdine](https://wowpedia.fandom.com/wiki/Auberdine "Auberdine"), [Rut'theran Village](https://wowpedia.fandom.com/wiki/Rut%27theran_Village "Rut'theran Village"), and [Feathermoon Stronghold](https://wowpedia.fandom.com/wiki/Feathermoon_Stronghold_(Classic) "Feathermoon Stronghold (Classic)"), forcing their residents to relocate — usually inland. Even far from the coast, fires, avalanches and lava eruptions changed some areas beyond recognition. The [Barrens](https://wowpedia.fandom.com/wiki/Barrens "Barrens") was split into two.

The tectonic shifts blocked some old routes, like the one between [Badlands](https://wowpedia.fandom.com/wiki/Badlands "Badlands") and [Loch Modan](https://wowpedia.fandom.com/wiki/Loch_Modan "Loch Modan"), and opened some new ones through previously impassable mountains. The Cataclysm also damaged an ancient [titan](https://wowpedia.fandom.com/wiki/Titan "Titan") device previously hiding the [Uldum](https://wowpedia.fandom.com/wiki/Uldum "Uldum") complex, exposing access to it from [Tanaris](https://wowpedia.fandom.com/wiki/Tanaris "Tanaris"). [Zandalar](https://wowpedia.fandom.com/wiki/Zandalar "Zandalar") was thought to have been severely crippled.<sup id="cite_ref-15"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-15">[15]</a></sup> Though this later proved to be an incorrect claim based on an inaccurate vision by Zul. It did, however, cause the region of Nazmir to lose elevation and become a swamp, and also destroyed the second seal holding the prison of [G'huun](https://wowpedia.fandom.com/wiki/G%27huun "G'huun").<sup id="cite_ref-16"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-16">[16]</a></sup>

Far out in the ocean, the [Wandering Isle](https://wowpedia.fandom.com/wiki/Wandering_Isle "Wandering Isle") experienced what [Chen Stormstout](https://wowpedia.fandom.com/wiki/Chen_Stormstout "Chen Stormstout") described as horrible waves.<sup id="cite_ref-17"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-17">[17]</a></sup>

The Cataclysm brought the [Elemental Plane](https://wowpedia.fandom.com/wiki/Elemental_Plane "Elemental Plane") closer to Azeroth, bringing the world in direct conflict with the elemental lords — including [Ragnaros](https://wowpedia.fandom.com/wiki/Ragnaros "Ragnaros"), who, upon his return, assaulted [Nordrassil](https://wowpedia.fandom.com/wiki/Nordrassil "Nordrassil"), prompting [Malfurion Stormrage](https://wowpedia.fandom.com/wiki/Malfurion_Stormrage "Malfurion Stormrage") to organize a defense of [Mount Hyjal](https://wowpedia.fandom.com/wiki/Mount_Hyjal "Mount Hyjal") again.

The [goblin](https://wowpedia.fandom.com/wiki/Goblin "Goblin") island of [Kezan](https://wowpedia.fandom.com/wiki/Kezan "Kezan") and the self-isolated nation of [Gilneas](https://wowpedia.fandom.com/wiki/Gilneas_(kingdom) "Gilneas (kingdom)") in the [peninsula of the same name](https://wowpedia.fandom.com/wiki/Gilneas_peninsula "Gilneas peninsula") suffered greatly from natural disasters, leading directly to events that affected the existing balance between the [Horde](https://wowpedia.fandom.com/wiki/Horde "Horde") and the [Alliance](https://wowpedia.fandom.com/wiki/Alliance "Alliance") respectively, redrawing the political map of the world. [Mount Kajaro](https://wowpedia.fandom.com/wiki/Mount_Kajaro "Mount Kajaro") on Kezan erupted, forcing an evacuation by the goblins. Earthquakes damaged the [Greymane Wall](https://wowpedia.fandom.com/wiki/Greymane_Wall "Greymane Wall") that had protected Gilneas by land and a coral reef that protected them by sea, opening them up to invasion by the [Forsaken](https://wowpedia.fandom.com/wiki/Forsaken "Forsaken") and the rest of the [Horde](https://wowpedia.fandom.com/wiki/Horde "Horde"). Large chunks of of the lands near the sea also ended up underwater in a manner of seconds.

During his last battle, Deathwing tried to summon the final Cataclysm. After the Aspect's death, [Thrall](https://wowpedia.fandom.com/wiki/Thrall "Thrall") concluded that the Cataclysm is over.

The [mists](https://wowpedia.fandom.com/wiki/Mists_of_Pandaria_(lore) "Mists of Pandaria (lore)") around [Pandaria](https://wowpedia.fandom.com/wiki/Pandaria "Pandaria") parted because of the Cataclysm.<sup id="cite_ref-18"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-18">[18]</a></sup>

The Cataclysm didn't only change the land, it also changed the sea, rendering old weather, tides, and navigation notes useless.<sup id="cite_ref-19"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-19">[19]</a></sup>

## Notes

-   Although [Dustwallow Marsh](https://wowpedia.fandom.com/wiki/Dustwallow_Marsh "Dustwallow Marsh") was not very updated and changed (only a highway added) in the game, the Cataclysm somehow affected the area lorewise.<sup id="cite_ref-20"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-20">[20]</a></sup>
-   The island of [Kul Tiras](https://wowpedia.fandom.com/wiki/Kul_Tiras "Kul Tiras") was originally stated to have been shifted out to sea because of the Cataclysm moving tectonic plates.<sup id="cite_ref-21"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-21">[21]</a></sup> This was retconned by _[World of Warcraft: Chronicle Volume 3](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Chronicle_Volume_3 "World of Warcraft: Chronicle Volume 3")_ which retroactively placed Kul Tiras near the [Broken Isles](https://wowpedia.fandom.com/wiki/Broken_Isles "Broken Isles"), in its _Battle for Azeroth_ location, before the Cataclysm.<sup id="cite_ref-22"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-22">[22]</a></sup>
-   It was originally suggested that one of the reasons the Cataclysm occurred was because the adventurers had defeated the Old Gods Yogg-Saron and C'Thun.<sup id="cite_ref-23"><a href="https://wowpedia.fandom.com/wiki/Cataclysm_(event)#cite_note-23">[23]</a></sup>

## References

Others like you also viewed