| [![Neutral](https://static.wikia.nocookie.net/wowpedia/images/1/19/Neutral_32.png/revision/latest?cb=20110620212507)](https://wowpedia.fandom.com/wiki/Faction "Neutral")Kaldorei Resistance |
| --- |
| [![Jarod Shadowsong TCG.jpg](https://static.wikia.nocookie.net/wowpedia/images/0/0c/Jarod_Shadowsong_TCG.jpg/revision/latest/scale-to-width-down/260?cb=20130502161100)](https://static.wikia.nocookie.net/wowpedia/images/0/0c/Jarod_Shadowsong_TCG.jpg/revision/latest?cb=20130502161100)
Jarod Shadowsong and resistance fighters

 |
| Main leader |  ![](https://static.wikia.nocookie.net/wowpedia/images/f/f4/IconSmall_Jarod.gif/revision/latest/scale-to-width-down/16?cb=20181211112543)[Jarod Shadowsong](https://wowpedia.fandom.com/wiki/Jarod_Shadowsong "Jarod Shadowsong") |
|   Formerly |  ![](https://static.wikia.nocookie.net/wowpedia/images/a/a8/IconSmall_Kur%27talos.gif/revision/latest/scale-to-width-down/16?cb=20180304142416)[Kur'talos Ravencrest](https://wowpedia.fandom.com/wiki/Kur%27talos_Ravencrest "Kur'talos Ravencrest") <sup>&nbsp;†</sup>  
 ![](https://static.wikia.nocookie.net/wowpedia/images/e/e8/IconSmall_NightElf_Male.gif/revision/latest/scale-to-width-down/16?cb=20200518005657)[Desdel Stareye](https://wowpedia.fandom.com/wiki/Desdel_Stareye "Desdel Stareye") <sup>&nbsp;†</sup> |
| Secondary leaders |  ![](https://static.wikia.nocookie.net/wowpedia/images/4/41/IconSmall_Malfurion.gif/revision/latest/scale-to-width-down/16?cb=20181211102211)[Malfurion Stormrage](https://wowpedia.fandom.com/wiki/Malfurion_Stormrage "Malfurion Stormrage")  
 ![](https://static.wikia.nocookie.net/wowpedia/images/b/b6/IconSmall_Tyrande.gif/revision/latest/scale-to-width-down/16?cb=20181211101823)[Tyrande Whisperwind](https://wowpedia.fandom.com/wiki/Tyrande_Whisperwind "Tyrande Whisperwind")  
 ![](https://static.wikia.nocookie.net/wowpedia/images/4/41/IconSmall_Tauren_Male.gif/revision/latest/scale-to-width-down/16?cb=20200519233641)[Huln Highmountain](https://wowpedia.fandom.com/wiki/Huln_Highmountain "Huln Highmountain")  
 ![](https://static.wikia.nocookie.net/wowpedia/images/8/85/IconSmall_EarthenSouth.gif/revision/latest/scale-to-width-down/16?cb=20200512184414)[Dungard Ironcutter](https://wowpedia.fandom.com/wiki/Dungard_Ironcutter "Dungard Ironcutter")  
 ![](https://static.wikia.nocookie.net/wowpedia/images/4/41/IconSmall_Furbolg.gif/revision/latest/scale-to-width-down/16?cb=20211118211011)[Unng Ak](https://wowpedia.fandom.com/wiki/Unng_Ak "Unng Ak")  
 ![](https://static.wikia.nocookie.net/wowpedia/images/6/6b/IconSmall_Cenarius.gif/revision/latest/scale-to-width-down/16?cb=20200519141117)[Cenarius](https://wowpedia.fandom.com/wiki/Cenarius "Cenarius")  
 ![](https://static.wikia.nocookie.net/wowpedia/images/0/07/IconSmall_Malorne.gif/revision/latest/scale-to-width-down/16?cb=20211213120610)[Malorne](https://wowpedia.fandom.com/wiki/Malorne "Malorne")  
 ![](https://static.wikia.nocookie.net/wowpedia/images/a/a1/IconSmall_Highborne_Male.gif/revision/latest/scale-to-width-down/16?cb=20200530181102)[Dath'Remar Sunstrider](https://wowpedia.fandom.com/wiki/Dath%27Remar_Sunstrider "Dath'Remar Sunstrider")  
 ![](https://static.wikia.nocookie.net/wowpedia/images/6/6f/IconSmall_Alexstrasza.gif/revision/latest/scale-to-width-down/16?cb=20211206105736)[Alexstrasza](https://wowpedia.fandom.com/wiki/Alexstrasza "Alexstrasza")  
 ![](https://static.wikia.nocookie.net/wowpedia/images/1/12/IconSmall_Malygos.gif/revision/latest/scale-to-width-down/16?cb=20211213120715)[Malygos](https://wowpedia.fandom.com/wiki/Malygos "Malygos")  
 ![](https://static.wikia.nocookie.net/wowpedia/images/e/e8/IconSmall_DragonBronze.gif/revision/latest/scale-to-width-down/16?cb=20211127102534)[Soridormi](https://wowpedia.fandom.com/wiki/Soridormi "Soridormi")  
 ![](https://static.wikia.nocookie.net/wowpedia/images/d/d5/IconSmall_YseraDragon.gif/revision/latest/scale-to-width-down/16?cb=20211214170852)[Ysera](https://wowpedia.fandom.com/wiki/Ysera "Ysera") |
|   Formerly |  ![](https://static.wikia.nocookie.net/wowpedia/images/1/18/IconSmall_NightElf_Female.gif/revision/latest/scale-to-width-down/16?cb=20200518010323)[Dejahna](https://wowpedia.fandom.com/wiki/Dejahna "Dejahna") <sup>&nbsp;†</sup>  
 ![](https://static.wikia.nocookie.net/wowpedia/images/6/6d/IconSmall_Deathwing.gif/revision/latest/scale-to-width-down/16?cb=20211210104433)[Neltharion](https://wowpedia.fandom.com/wiki/Deathwing "Deathwing") |
| Race(s) | [![Night elf](https://static.wikia.nocookie.net/wowpedia/images/e/e8/IconSmall_NightElf_Male.gif/revision/latest/scale-to-width-down/16?cb=20200518005657)](https://wowpedia.fandom.com/wiki/Night_elf "Night elf")[![Night elf](https://static.wikia.nocookie.net/wowpedia/images/1/18/IconSmall_NightElf_Female.gif/revision/latest/scale-to-width-down/16?cb=20200518010323)](https://wowpedia.fandom.com/wiki/Night_elf "Night elf") [Night elf](https://wowpedia.fandom.com/wiki/Night_elf "Night elf")  
[![Highborne](https://static.wikia.nocookie.net/wowpedia/images/a/a1/IconSmall_Highborne_Male.gif/revision/latest/scale-to-width-down/16?cb=20200530181102)](https://wowpedia.fandom.com/wiki/Highborne "Highborne")[![Highborne](https://static.wikia.nocookie.net/wowpedia/images/1/1c/IconSmall_Highborne_Female.gif/revision/latest/scale-to-width-down/16?cb=20200530212600)](https://wowpedia.fandom.com/wiki/Highborne "Highborne") [Highborne](https://wowpedia.fandom.com/wiki/Highborne "Highborne")  
[![Furbolg](https://static.wikia.nocookie.net/wowpedia/images/4/41/IconSmall_Furbolg.gif/revision/latest/scale-to-width-down/16?cb=20211118211011)](https://wowpedia.fandom.com/wiki/Furbolg "Furbolg") [Furbolg](https://wowpedia.fandom.com/wiki/Furbolg "Furbolg")  
[![Tauren](https://static.wikia.nocookie.net/wowpedia/images/4/41/IconSmall_Tauren_Male.gif/revision/latest/scale-to-width-down/16?cb=20200519233641)](https://wowpedia.fandom.com/wiki/Tauren "Tauren")[![Tauren](https://static.wikia.nocookie.net/wowpedia/images/3/30/IconSmall_Tauren_Female.gif/revision/latest/scale-to-width-down/16?cb=20200520000847)](https://wowpedia.fandom.com/wiki/Tauren "Tauren") [Tauren](https://wowpedia.fandom.com/wiki/Tauren "Tauren")  
[![Earthen](https://static.wikia.nocookie.net/wowpedia/images/8/85/IconSmall_EarthenSouth.gif/revision/latest/scale-to-width-down/16?cb=20200512184414)](https://wowpedia.fandom.com/wiki/Earthen "Earthen")[![Earthen](https://static.wikia.nocookie.net/wowpedia/images/c/c6/IconSmall_EarthenNorth.gif/revision/latest/scale-to-width-down/16?cb=20200520104145)](https://wowpedia.fandom.com/wiki/Earthen "Earthen") [Earthen](https://wowpedia.fandom.com/wiki/Earthen "Earthen")  
[![Keeper of the grove](https://static.wikia.nocookie.net/wowpedia/images/6/6e/IconSmall_Cenarian_Male.gif/revision/latest/scale-to-width-down/16?cb=20200519150626)](https://wowpedia.fandom.com/wiki/Keeper_of_the_grove "Keeper of the grove") [Keeper of the grove](https://wowpedia.fandom.com/wiki/Keeper_of_the_grove "Keeper of the grove")  
[![Dryad](https://static.wikia.nocookie.net/wowpedia/images/1/1c/IconSmall_Cenarian_Female.gif/revision/latest/scale-to-width-down/16?cb=20200519163859)](https://wowpedia.fandom.com/wiki/Dryad "Dryad") [Dryad](https://wowpedia.fandom.com/wiki/Dryad "Dryad")  
[![IconSmall Cenarius.gif](https://static.wikia.nocookie.net/wowpedia/images/6/6b/IconSmall_Cenarius.gif/revision/latest/scale-to-width-down/16?cb=20200519141117)](https://static.wikia.nocookie.net/wowpedia/images/6/6b/IconSmall_Cenarius.gif/revision/latest?cb=20200519141117)[![IconSmall Agamaggan.gif](https://static.wikia.nocookie.net/wowpedia/images/8/83/IconSmall_Agamaggan.gif/revision/latest/scale-to-width-down/16?cb=20221014202406)](https://static.wikia.nocookie.net/wowpedia/images/8/83/IconSmall_Agamaggan.gif/revision/latest?cb=20221014202406)[![IconSmall Ashamane.gif](https://static.wikia.nocookie.net/wowpedia/images/3/3f/IconSmall_Ashamane.gif/revision/latest/scale-to-width-down/16?cb=20211210181048)](https://static.wikia.nocookie.net/wowpedia/images/3/3f/IconSmall_Ashamane.gif/revision/latest?cb=20211210181048)[![IconSmall Aviana.gif](https://static.wikia.nocookie.net/wowpedia/images/f/f4/IconSmall_Aviana.gif/revision/latest/scale-to-width-down/16?cb=20211118213213)](https://static.wikia.nocookie.net/wowpedia/images/f/f4/IconSmall_Aviana.gif/revision/latest?cb=20211118213213)[![IconSmall Goldrinn.gif](https://static.wikia.nocookie.net/wowpedia/images/9/9b/IconSmall_Goldrinn.gif/revision/latest/scale-to-width-down/16?cb=20221014204046)](https://static.wikia.nocookie.net/wowpedia/images/9/9b/IconSmall_Goldrinn.gif/revision/latest?cb=20221014204046)[![IconSmall Malorne.gif](https://static.wikia.nocookie.net/wowpedia/images/0/07/IconSmall_Malorne.gif/revision/latest/scale-to-width-down/16?cb=20211213120610)](https://static.wikia.nocookie.net/wowpedia/images/0/07/IconSmall_Malorne.gif/revision/latest?cb=20211213120610) [Ancient Guardians](https://wowpedia.fandom.com/wiki/Ancient_Guardian "Ancient Guardian")  
[![IconSmall SpawnBlue.gif](https://static.wikia.nocookie.net/wowpedia/images/6/6e/IconSmall_SpawnBlue_Male.gif/revision/latest/scale-to-width-down/16?cb=20211129100153)](https://static.wikia.nocookie.net/wowpedia/images/6/6e/IconSmall_SpawnBlue_Male.gif/revision/latest?cb=20211129100153)[![IconSmall DrakonidBlue.gif](https://static.wikia.nocookie.net/wowpedia/images/d/d7/IconSmall_DrakonidBlue.gif/revision/latest/scale-to-width-down/16?cb=20211127104037)](https://static.wikia.nocookie.net/wowpedia/images/d/d7/IconSmall_DrakonidBlue.gif/revision/latest?cb=20211127104037)[![Blue dragon](https://static.wikia.nocookie.net/wowpedia/images/a/af/IconSmall_DragonBlue2.gif/revision/latest/scale-to-width-down/16?cb=20221208133249)](https://wowpedia.fandom.com/wiki/Blue_dragon "Blue dragon") [Blue dragon](https://wowpedia.fandom.com/wiki/Blue_dragon "Blue dragon")  
[![IconSmall SpawnBronze.gif](https://static.wikia.nocookie.net/wowpedia/images/2/2c/IconSmall_SpawnBronze_Male.gif/revision/latest/scale-to-width-down/16?cb=20211129100141)](https://static.wikia.nocookie.net/wowpedia/images/2/2c/IconSmall_SpawnBronze_Male.gif/revision/latest?cb=20211129100141)[![IconSmall DrakonidBronze.gif](https://static.wikia.nocookie.net/wowpedia/images/b/bc/IconSmall_DrakonidBronze.gif/revision/latest/scale-to-width-down/16?cb=20211127104110)](https://static.wikia.nocookie.net/wowpedia/images/b/bc/IconSmall_DrakonidBronze.gif/revision/latest?cb=20211127104110)[![Bronze dragon](https://static.wikia.nocookie.net/wowpedia/images/5/53/IconSmall_DragonBronze2.gif/revision/latest/scale-to-width-down/16?cb=20221208133255)](https://wowpedia.fandom.com/wiki/Bronze_dragon "Bronze dragon") [Bronze dragon](https://wowpedia.fandom.com/wiki/Bronze_dragon "Bronze dragon")  
[![IconSmall SpawnGreen.gif](https://static.wikia.nocookie.net/wowpedia/images/c/c6/IconSmall_SpawnGreen_Male.gif/revision/latest/scale-to-width-down/16?cb=20211129100127)](https://static.wikia.nocookie.net/wowpedia/images/c/c6/IconSmall_SpawnGreen_Male.gif/revision/latest?cb=20211129100127)[![IconSmall DrakonidGreen.gif](https://static.wikia.nocookie.net/wowpedia/images/3/31/IconSmall_DrakonidGreen.gif/revision/latest/scale-to-width-down/16?cb=20211127104127)](https://static.wikia.nocookie.net/wowpedia/images/3/31/IconSmall_DrakonidGreen.gif/revision/latest?cb=20211127104127)[![Green dragon](https://static.wikia.nocookie.net/wowpedia/images/0/0a/IconSmall_DragonGreen2.gif/revision/latest/scale-to-width-down/16?cb=20221208133302)](https://wowpedia.fandom.com/wiki/Green_dragon "Green dragon") [Green dragon](https://wowpedia.fandom.com/wiki/Green_dragon "Green dragon")  
[![IconSmall SpawnRed.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/0/04/IconSmall_SpawnRed_Male.gif/revision/latest?cb=20211129100121)[![IconSmall DrakonidRed.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/e/e9/IconSmall_DrakonidRed.gif/revision/latest?cb=20211127104133)[![Red dragon](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://wowpedia.fandom.com/wiki/Red_dragon "Red dragon") [Red dragon](https://wowpedia.fandom.com/wiki/Red_dragon "Red dragon")  
[![IconSmall Human Male.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/e/ee/IconSmall_Human_Male.gif/revision/latest?cb=20200518004645) [Human](https://wowpedia.fandom.com/wiki/Human "Human") (1)  
[![IconSmall Orc Male.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/3/3c/IconSmall_Orc_Male.gif/revision/latest?cb=20200518012003) [Orc](https://wowpedia.fandom.com/wiki/Orc "Orc") (1) |
|   Formerly | [![IconSmall SpawnBlack.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/f/f6/IconSmall_SpawnBlack_Male.gif/revision/latest?cb=20211129100202)[![IconSmall DrakonidBlack.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/7/75/IconSmall_DrakonidBlack.gif/revision/latest?cb=20211127104034)[![Black dragon](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://wowpedia.fandom.com/wiki/Black_dragon "Black dragon") [Black dragon](https://wowpedia.fandom.com/wiki/Black_dragon "Black dragon") |
| Base of operations | [Black Rook Hold](https://wowpedia.fandom.com/wiki/Black_Rook_Hold "Black Rook Hold") |
| Theater of operations | [Ancient Kalimdor](https://wowpedia.fandom.com/wiki/Ancient_Kalimdor "Ancient Kalimdor") |
| Language(s) | [Darnassian](https://wowpedia.fandom.com/wiki/Darnassian "Darnassian"), [Draconic](https://wowpedia.fandom.com/wiki/Draconic "Draconic"), [Furbolg](https://wowpedia.fandom.com/wiki/Furbolg_(language) "Furbolg (language)"), [Taur-ahe](https://wowpedia.fandom.com/wiki/Taur-ahe "Taur-ahe"), [Earthen language](https://wowpedia.fandom.com/wiki/Titan_(language) "Titan (language)") |
| Affiliation | [Independent](https://wowpedia.fandom.com/wiki/Independent "Independent") |
| Status | Disbanded after the [Great Sundering](https://wowpedia.fandom.com/wiki/Great_Sundering "Great Sundering") |

The **Kaldorei Resistance**,<sup id="cite_ref-1"><a href="https://wowpedia.fandom.com/wiki/Kaldorei_Resistance#cite_note-1">[1]</a></sup><sup id="cite_ref-2"><a href="https://wowpedia.fandom.com/wiki/Kaldorei_Resistance#cite_note-2">[2]</a></sup><sup id="cite_ref-3"><a href="https://wowpedia.fandom.com/wiki/Kaldorei_Resistance#cite_note-3">[3]</a></sup> or **night elf resistance**,<sup id="cite_ref-4"><a href="https://wowpedia.fandom.com/wiki/Kaldorei_Resistance#cite_note-4">[4]</a></sup> were those who fought against the [Burning Legion](https://wowpedia.fandom.com/wiki/Burning_Legion "Burning Legion") and the [Highborne](https://wowpedia.fandom.com/wiki/Highborne "Highborne") leaders from the [Kaldorei Empire](https://wowpedia.fandom.com/wiki/Kaldorei_Empire "Kaldorei Empire"). They were led by [Lord Ravencrest](https://wowpedia.fandom.com/wiki/Lord_Ravencrest "Lord Ravencrest").<sup id="cite_ref-5"><a href="https://wowpedia.fandom.com/wiki/Kaldorei_Resistance#cite_note-5">[5]</a></sup> The Resistance consisted of several night elven organizations including the [Moon Guard](https://wowpedia.fandom.com/wiki/Moon_Guard "Moon Guard"), [Sisterhood of Elune](https://wowpedia.fandom.com/wiki/Sisterhood_of_Elune "Sisterhood of Elune"), the [Rooksguard](https://wowpedia.fandom.com/wiki/Rooksguard "Rooksguard"), and the denizens like the [Wild Gods](https://wowpedia.fandom.com/wiki/Wild_God "Wild God") and the [dragonflights](https://wowpedia.fandom.com/wiki/Dragonflight "Dragonflight").

The host almost entirely consisted out of [night elves](https://wowpedia.fandom.com/wiki/Night_elf "Night elf") at the beginning at the war, but towards the end, thanks to Krasus, [tauren](https://wowpedia.fandom.com/wiki/Tauren "Tauren"), [earthen](https://wowpedia.fandom.com/wiki/Earthen "Earthen") and even [furbolgs](https://wowpedia.fandom.com/wiki/Furbolg "Furbolg") joined, adding more melee power the night elves needed.<sup><a href="https://wowpedia.fandom.com/wiki/Wowpedia:Citation" title="Wowpedia:Citation">[<span title="Cited as Sund - but what page?"><i>citation needed</i></span>]</a></sup> 

They eventually defeated the Burning Legion.

## Member organizations

-   [Moon Guard](https://wowpedia.fandom.com/wiki/Moon_Guard "Moon Guard")
-   [Sisterhood of Elune](https://wowpedia.fandom.com/wiki/Sisterhood_of_Elune "Sisterhood of Elune")
-   [Rooksguard](https://wowpedia.fandom.com/wiki/Rooksguard "Rooksguard")
-   [Dragonflights](https://wowpedia.fandom.com/wiki/Dragonflight "Dragonflight")
-   Many others

## Members

### Notable

| Name | Role | Status | Location |
| --- | --- | --- | --- |
| [![Neutral](https://static.wikia.nocookie.net/wowpedia/images/c/cb/Neutral_15.png/revision/latest?cb=20110620220434)](https://wowpedia.fandom.com/wiki/Faction "Neutral")[![IconSmall Kur'talos.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/a/a8/IconSmall_Kur%27talos.gif/revision/latest?cb=20180304142416) [Kur'talos Ravencrest](https://wowpedia.fandom.com/wiki/Kur%27talos_Ravencrest "Kur'talos Ravencrest") | Supreme Commander (antepenultimate) | Active (spirit) | [Various](https://wowpedia.fandom.com/wiki/Kur%27talos_Ravencrest#Locations "Kur'talos Ravencrest") |
| [![Horde](https://static.wikia.nocookie.net/wowpedia/images/c/c4/Horde_15.png/revision/latest?cb=20201010153315)](https://wowpedia.fandom.com/wiki/Horde "Horde")[![IconSmall Broxigar.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/f/fb/IconSmall_Broxigar.gif/revision/latest?cb=20200520162358) [Broxigar](https://wowpedia.fandom.com/wiki/Broxigar "Broxigar") | Warrior, Time-traveler | Deceased |  |
| [![Neutral](https://static.wikia.nocookie.net/wowpedia/images/c/cb/Neutral_15.png/revision/latest?cb=20110620220434)](https://wowpedia.fandom.com/wiki/Faction "Neutral")[![IconSmall Stormrage.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/a/a3/IconSmall_Stormrage.gif/revision/latest?cb=20211211102521) [Illidan Stormrage](https://wowpedia.fandom.com/wiki/Illidan_Stormrage "Illidan Stormrage") | Part of the [Moon Guard](https://wowpedia.fandom.com/wiki/Moon_Guard "Moon Guard") until betrayal. | Alive | [Various](https://wowpedia.fandom.com/wiki/Illidan_Stormrage#Locations "Illidan Stormrage") |
| [![Neutral](https://static.wikia.nocookie.net/wowpedia/images/c/cb/Neutral_15.png/revision/latest?cb=20110620220434)](https://wowpedia.fandom.com/wiki/Faction "Neutral")[![IconSmall Malfurion.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/4/41/IconSmall_Malfurion.gif/revision/latest?cb=20181211102211) [Malfurion Stormrage](https://wowpedia.fandom.com/wiki/Malfurion_Stormrage "Malfurion Stormrage") | Druid | Alive | [Various](https://wowpedia.fandom.com/wiki/Malfurion_Stormrage#Locations "Malfurion Stormrage") |  |
| [![Neutral](https://static.wikia.nocookie.net/wowpedia/images/c/cb/Neutral_15.png/revision/latest?cb=20110620220434)](https://wowpedia.fandom.com/wiki/Faction "Neutral")[![IconSmall NightElf Male.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/e/e8/IconSmall_NightElf_Male.gif/revision/latest?cb=20200518005657) [Desdel Stareye](https://wowpedia.fandom.com/wiki/Desdel_Stareye "Desdel Stareye") | Supreme Commander (penultimate) | Deceased |  |
| [![Neutral](https://static.wikia.nocookie.net/wowpedia/images/c/cb/Neutral_15.png/revision/latest?cb=20110620220434)](https://wowpedia.fandom.com/wiki/Faction "Neutral")[![IconSmall Rhonin.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/3/36/IconSmall_Rhonin.gif/revision/latest?cb=20180226102447) [Rhonin](https://wowpedia.fandom.com/wiki/Rhonin "Rhonin") | Part, later leader of the [Moon Guard](https://wowpedia.fandom.com/wiki/Moon_Guard "Moon Guard"), Time traveler | Deceased | [Various](https://wowpedia.fandom.com/wiki/Rhonin#Locations "Rhonin") |
| [![Neutral](https://static.wikia.nocookie.net/wowpedia/images/c/cb/Neutral_15.png/revision/latest?cb=20110620220434)](https://wowpedia.fandom.com/wiki/Faction "Neutral")[![IconSmall Krasus.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/8/8f/IconSmall_Krasus.gif/revision/latest?cb=20200530091715) [Krasus](https://wowpedia.fandom.com/wiki/Krasus "Krasus") | Consort of [Alexstrasza](https://wowpedia.fandom.com/wiki/Alexstrasza "Alexstrasza"), Time-traveler | Deceased | [Various](https://wowpedia.fandom.com/wiki/Krasus#Locations "Krasus") |  |
| [![Neutral](https://static.wikia.nocookie.net/wowpedia/images/c/cb/Neutral_15.png/revision/latest?cb=20110620220434)](https://wowpedia.fandom.com/wiki/Faction "Neutral")[![IconSmall Tyrande.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/b/b6/IconSmall_Tyrande.gif/revision/latest?cb=20181211101823) [Tyrande Whisperwind](https://wowpedia.fandom.com/wiki/Tyrande_Whisperwind "Tyrande Whisperwind") | High Priestess | Alive | [Various](https://wowpedia.fandom.com/wiki/Tyrande_Whisperwind#Locations "Tyrande Whisperwind") |  |
| [![Neutral](https://static.wikia.nocookie.net/wowpedia/images/c/cb/Neutral_15.png/revision/latest?cb=20110620220434)](https://wowpedia.fandom.com/wiki/Faction "Neutral")[![IconSmall Maiev.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/6/6b/IconSmall_Maiev.gif/revision/latest?cb=20181211112206) [Maiev Shadowsong](https://wowpedia.fandom.com/wiki/Maiev_Shadowsong "Maiev Shadowsong") | Priestess | Alive | [Various](https://wowpedia.fandom.com/wiki/Maiev_Shadowsong#Locations "Maiev Shadowsong") |
| [![Neutral](https://static.wikia.nocookie.net/wowpedia/images/c/cb/Neutral_15.png/revision/latest?cb=20110620220434)](https://wowpedia.fandom.com/wiki/Faction "Neutral")[![IconSmall Highmountain Male.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/3/3c/IconSmall_Highmountain_Male.gif/revision/latest?cb=20200520042932) [Huln Highmountain](https://wowpedia.fandom.com/wiki/Huln_Highmountain "Huln Highmountain") | Spokesmen for the Tauren tribes | Deceased after the war |
| [![Neutral](https://static.wikia.nocookie.net/wowpedia/images/c/cb/Neutral_15.png/revision/latest?cb=20110620220434)](https://wowpedia.fandom.com/wiki/Faction "Neutral")[![IconSmall Jarod.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/f/f4/IconSmall_Jarod.gif/revision/latest?cb=20181211112543) [Jarod Shadowsong](https://wowpedia.fandom.com/wiki/Jarod_Shadowsong "Jarod Shadowsong") | Supreme Commander (last) | Alive | [Various](https://wowpedia.fandom.com/wiki/Jarod_Shadowsong#Locations "Jarod Shadowsong") |
| [![Neutral](https://static.wikia.nocookie.net/wowpedia/images/c/cb/Neutral_15.png/revision/latest?cb=20110620220434)](https://wowpedia.fandom.com/wiki/Faction "Neutral")[![IconSmall EarthenSouth.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/8/85/IconSmall_EarthenSouth.gif/revision/latest?cb=20200512184414) [Dungard Ironcutter](https://wowpedia.fandom.com/wiki/Dungard_Ironcutter "Dungard Ironcutter") | Spokesmen for the Earthen | Unknown |
| [![Neutral](https://static.wikia.nocookie.net/wowpedia/images/c/cb/Neutral_15.png/revision/latest?cb=20110620220434)](https://wowpedia.fandom.com/wiki/Faction "Neutral")[![IconSmall Furbolg.gif](data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D)](https://static.wikia.nocookie.net/wowpedia/images/4/41/IconSmall_Furbolg.gif/revision/latest?cb=20211118211011) [Unng Ak](https://wowpedia.fandom.com/wiki/Unng_Ak "Unng Ak") | Spokesmen for the Furbolg tribes | Deceased after the war |

### Minor

## References

1.  [^](https://wowpedia.fandom.com/wiki/Kaldorei_Resistance#cite_ref-1) _[Ultimate Visual Guide](https://wowpedia.fandom.com/wiki/Ultimate_Visual_Guide "Ultimate Visual Guide")_, pg. 92
2.  [^](https://wowpedia.fandom.com/wiki/Kaldorei_Resistance#cite_ref-2) Lord Kur'talos Ravencrest (War of the Ancients)
3.  [^](https://wowpedia.fandom.com/wiki/Kaldorei_Resistance#cite_ref-3) [Kur'talos Ravencrest (tactics)#Dungeon Journal](https://wowpedia.fandom.com/wiki/Kur%27talos_Ravencrest_(tactics)#Dungeon_Journal "Kur'talos Ravencrest (tactics)")
4.  [^](https://wowpedia.fandom.com/wiki/Kaldorei_Resistance#cite_ref-4) [Worn-Edged Page](https://wowpedia.fandom.com/wiki/Worn-Edged_Page "Worn-Edged Page")
5.  [^](https://wowpedia.fandom.com/wiki/Kaldorei_Resistance#cite_ref-5) [Knaak, Richard A.](https://wowpedia.fandom.com/wiki/Richard_A._Knaak "Richard A. Knaak"). _[The Well of Eternity](https://wowpedia.fandom.com/wiki/The_Well_of_Eternity "The Well of Eternity")_, 297. [ISBN 978-0-7434-8902-7](https://wowpedia.fandom.com/wiki/Special:BookSources/9780743489027). 

Others like you also viewed