_For the priest talent, see  ![](https://static.wikia.nocookie.net/wowpedia/images/8/8c/Spell_holy_holysmite.png/revision/latest/scale-to-width-down/16?cb=20060930061021)[\[Sanctuary\]](https://wowpedia.fandom.com/wiki/Sanctuary_(priest_talent)). For the removed paladin talent, see  ![](https://static.wikia.nocookie.net/wowpedia/images/f/f9/Spell_nature_lightningshield.png/revision/latest/scale-to-width-down/16?cb=20060923182031)[\[Sanctuary\]](https://wowpedia.fandom.com/wiki/Sanctuary_(paladin_talent))._

A **sanctuary** is an area where [PvP](https://wowpedia.fandom.com/wiki/PvP "PvP") combat is disabled for all players, and turning on your PvP flag will have no effect until you leave the sanctuary. Sanctuaries were introduced in _[World of Warcraft: The Burning Crusade](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_The_Burning_Crusade "World of Warcraft: The Burning Crusade")_. Places like [Nighthaven](https://wowpedia.fandom.com/wiki/Nighthaven "Nighthaven") and [Booty Bay](https://wowpedia.fandom.com/wiki/Booty_Bay "Booty Bay") are not sanctuaries; PvP combat is still possible there. Just because PvP combat is disabled, that does not mean that a sanctuary is a safe haven; for example, the monsters on the [Stair of Destiny](https://wowpedia.fandom.com/wiki/Stair_of_Destiny "Stair of Destiny") are not PvP NPCs and will attack players if aggroed.

Entering a sanctuary differs from the effect of manually turning off one's PvP flag, (or, on PvP servers, entering a friendly territory) in that PvP combat is _immediately_ disabled; there is no five minute wait. Because of this, it is possible to evade PvP combat by entering a sanctuary; for example, if someone is attacked by another player on their way to the [Dark Portal](https://wowpedia.fandom.com/wiki/Dark_Portal "Dark Portal") in the [Blasted Lands](https://wowpedia.fandom.com/wiki/Blasted_Lands "Blasted Lands"), their attacker cannot continue attacking them if they cross the portal and enter the [Stair of Destiny](https://wowpedia.fandom.com/wiki/Stair_of_Destiny "Stair of Destiny").

## List of sanctuaries

-   [The Stair of Destiny](https://wowpedia.fandom.com/wiki/Stair_of_Destiny "Stair of Destiny"), [Hellfire Peninsula](https://wowpedia.fandom.com/wiki/Hellfire_Peninsula "Hellfire Peninsula") [![Bc icon.gif](https://static.wikia.nocookie.net/wowpedia/images/0/0e/Bc_icon.gif/revision/latest?cb=20110218184702)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_The_Burning_Crusade "World of Warcraft: The Burning Crusade")
-   [Shattrath City](https://wowpedia.fandom.com/wiki/Shattrath_City "Shattrath City"), [Terokkar Forest](https://wowpedia.fandom.com/wiki/Terokkar_Forest "Terokkar Forest") [![Bc icon.gif](https://static.wikia.nocookie.net/wowpedia/images/0/0e/Bc_icon.gif/revision/latest?cb=20110218184702)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_The_Burning_Crusade "World of Warcraft: The Burning Crusade")
-   [Acherus: The Ebon Hold](https://wowpedia.fandom.com/wiki/Acherus:_The_Ebon_Hold "Acherus: The Ebon Hold"), [Eastern Plaguelands](https://wowpedia.fandom.com/wiki/Eastern_Plaguelands "Eastern Plaguelands") [![Wrath of the Lich King](https://static.wikia.nocookie.net/wowpedia/images/c/c1/Wrath-Logo-Small.png/revision/latest?cb=20090403101742)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Wrath_of_the_Lich_King "Wrath of the Lich King"), [Broken Isles](https://wowpedia.fandom.com/wiki/Broken_Isles "Broken Isles") [![Legion](https://static.wikia.nocookie.net/wowpedia/images/f/fd/Legion-Logo-Small.png/revision/latest?cb=20150808040028)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Legion "Legion")
-   [Dalaran](https://wowpedia.fandom.com/wiki/Dalaran "Dalaran"), [Crystalsong Forest](https://wowpedia.fandom.com/wiki/Crystalsong_Forest "Crystalsong Forest") [![Wrath of the Lich King](https://static.wikia.nocookie.net/wowpedia/images/c/c1/Wrath-Logo-Small.png/revision/latest?cb=20090403101742)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Wrath_of_the_Lich_King "Wrath of the Lich King")
-   [Angrathar the Wrathgate](https://wowpedia.fandom.com/wiki/Angrathar_the_Wrathgate "Angrathar the Wrathgate"), [Dragonblight](https://wowpedia.fandom.com/wiki/Dragonblight "Dragonblight") [![Wrath of the Lich King](https://static.wikia.nocookie.net/wowpedia/images/c/c1/Wrath-Logo-Small.png/revision/latest?cb=20090403101742)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Wrath_of_the_Lich_King "Wrath of the Lich King") (via an area-wide buff and only after having completed the Wrathgate questline)
-   [Argent Tournament Grounds](https://wowpedia.fandom.com/wiki/Argent_Tournament_Grounds "Argent Tournament Grounds"), [Icecrown](https://wowpedia.fandom.com/wiki/Icecrown "Icecrown") [![Wrath of the Lich King](https://static.wikia.nocookie.net/wowpedia/images/c/c1/Wrath-Logo-Small.png/revision/latest?cb=20090403101742)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Wrath_of_the_Lich_King "Wrath of the Lich King") (via an area-wide buff)
-   [The Frozen Halls](https://wowpedia.fandom.com/wiki/Frozen_Halls "Frozen Halls"), [Icecrown Citadel](https://wowpedia.fandom.com/wiki/Icecrown_Citadel "Icecrown Citadel"), [Icecrown](https://wowpedia.fandom.com/wiki/Icecrown "Icecrown") [![Wrath of the Lich King](https://static.wikia.nocookie.net/wowpedia/images/c/c1/Wrath-Logo-Small.png/revision/latest?cb=20090403101742)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Wrath_of_the_Lich_King "Wrath of the Lich King")
-   [The Maelstrom](https://wowpedia.fandom.com/wiki/Maelstrom "Maelstrom") [![Cataclysm](https://static.wikia.nocookie.net/wowpedia/images/e/ef/Cata-Logo-Small.png/revision/latest?cb=20120818171714)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Cataclysm "Cataclysm")
-   [Temple of Earth](https://wowpedia.fandom.com/wiki/Temple_of_Earth "Temple of Earth"), [Deepholm](https://wowpedia.fandom.com/wiki/Deepholm "Deepholm") [![Cataclysm](https://static.wikia.nocookie.net/wowpedia/images/e/ef/Cata-Logo-Small.png/revision/latest?cb=20120818171714)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Cataclysm "Cataclysm")
-   [Malfurion's Breach](https://wowpedia.fandom.com/wiki/Malfurion%27s_Breach "Malfurion's Breach"), [Molten Front](https://wowpedia.fandom.com/wiki/Molten_Front "Molten Front") [![Cataclysm](https://static.wikia.nocookie.net/wowpedia/images/e/ef/Cata-Logo-Small.png/revision/latest?cb=20120818171714)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Cataclysm "Cataclysm")
-   [Darkmoon Island](https://wowpedia.fandom.com/wiki/Darkmoon_Island "Darkmoon Island") [![Cataclysm](https://static.wikia.nocookie.net/wowpedia/images/e/ef/Cata-Logo-Small.png/revision/latest?cb=20120818171714)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Cataclysm "Cataclysm")
-   [Peak of Serenity](https://wowpedia.fandom.com/wiki/Peak_of_Serenity "Peak of Serenity"), [Kun-Lai Summit](https://wowpedia.fandom.com/wiki/Kun-Lai_Summit "Kun-Lai Summit") [![Mists of Pandaria](https://static.wikia.nocookie.net/wowpedia/images/2/26/Mists-Logo-Small.png/revision/latest?cb=20120407193524)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Mists_of_Pandaria "Mists of Pandaria")
-   [Razor Hill Watchtower](https://wowpedia.fandom.com/wiki/Razor_Hill_Watchtower "Razor Hill Watchtower"), [Durotar](https://wowpedia.fandom.com/wiki/Durotar "Durotar") [![Mists of Pandaria](https://static.wikia.nocookie.net/wowpedia/images/2/26/Mists-Logo-Small.png/revision/latest?cb=20120407193524)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Mists_of_Pandaria "Mists of Pandaria")\- [Patch 5.3.0](https://wowpedia.fandom.com/wiki/Patch_5.3.0 "Patch 5.3.0")
-   [Dalaran](https://wowpedia.fandom.com/wiki/Dalaran "Dalaran"), [Broken Isles](https://wowpedia.fandom.com/wiki/Broken_Isles "Broken Isles") [![Legion](https://static.wikia.nocookie.net/wowpedia/images/f/fd/Legion-Logo-Small.png/revision/latest?cb=20150808040028)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Legion "Legion")
-   [Hall of Shadows](https://wowpedia.fandom.com/wiki/Hall_of_Shadows "Hall of Shadows"), [Dalaran](https://wowpedia.fandom.com/wiki/Dalaran "Dalaran") [![Legion](https://static.wikia.nocookie.net/wowpedia/images/f/fd/Legion-Logo-Small.png/revision/latest?cb=20150808040028)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Legion "Legion")
-   [Dreadscar Rift](https://wowpedia.fandom.com/wiki/Dreadscar_Rift "Dreadscar Rift") [![Legion](https://static.wikia.nocookie.net/wowpedia/images/f/fd/Legion-Logo-Small.png/revision/latest?cb=20150808040028)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Legion "Legion")
-   [Hall of the Guardian](https://wowpedia.fandom.com/wiki/Hall_of_the_Guardian "Hall of the Guardian"), [Dalaran](https://wowpedia.fandom.com/wiki/Dalaran "Dalaran") [![Legion](https://static.wikia.nocookie.net/wowpedia/images/f/fd/Legion-Logo-Small.png/revision/latest?cb=20150808040028)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Legion "Legion")
-   [Heart of Azeroth](https://wowpedia.fandom.com/wiki/Heart_of_Azeroth_(Class_Hall) "Heart of Azeroth (Class Hall)"), [The Maelstrom](https://wowpedia.fandom.com/wiki/Maelstrom "Maelstrom") [![Legion](https://static.wikia.nocookie.net/wowpedia/images/f/fd/Legion-Logo-Small.png/revision/latest?cb=20150808040028)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Legion "Legion")
-   [Light's Hope Chapel](https://wowpedia.fandom.com/wiki/Light%27s_Hope_Chapel "Light's Hope Chapel"), [Eastern Plaguelands](https://wowpedia.fandom.com/wiki/Eastern_Plaguelands "Eastern Plaguelands") [![Legion](https://static.wikia.nocookie.net/wowpedia/images/f/fd/Legion-Logo-Small.png/revision/latest?cb=20150808040028)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Legion "Legion")
-   [Netherlight Temple](https://wowpedia.fandom.com/wiki/Netherlight_Temple "Netherlight Temple") [![Legion](https://static.wikia.nocookie.net/wowpedia/images/f/fd/Legion-Logo-Small.png/revision/latest?cb=20150808040028)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Legion "Legion")
-   [Sanctum of Light](https://wowpedia.fandom.com/wiki/Sanctum_of_Light "Sanctum of Light"), [Eastern Plaguelands](https://wowpedia.fandom.com/wiki/Eastern_Plaguelands "Eastern Plaguelands") [![Legion](https://static.wikia.nocookie.net/wowpedia/images/f/fd/Legion-Logo-Small.png/revision/latest?cb=20150808040028)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Legion "Legion")
-   [Shal'Aran](https://wowpedia.fandom.com/wiki/Shal%27Aran "Shal'Aran"), [Suramar](https://wowpedia.fandom.com/wiki/Suramar "Suramar") [![Legion](https://static.wikia.nocookie.net/wowpedia/images/f/fd/Legion-Logo-Small.png/revision/latest?cb=20150808040028)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Legion "Legion")
-   [Skyhold](https://wowpedia.fandom.com/wiki/Skyhold "Skyhold"), [Stormheim](https://wowpedia.fandom.com/wiki/Stormheim "Stormheim") [![Legion](https://static.wikia.nocookie.net/wowpedia/images/f/fd/Legion-Logo-Small.png/revision/latest?cb=20150808040028)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Legion "Legion")
-   [Temple of Five Dawns](https://wowpedia.fandom.com/wiki/Temple_of_Five_Dawns "Temple of Five Dawns"), [The Wandering Isle](https://wowpedia.fandom.com/wiki/Wandering_Isle "Wandering Isle") [![Legion](https://static.wikia.nocookie.net/wowpedia/images/f/fd/Legion-Logo-Small.png/revision/latest?cb=20150808040028)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Legion "Legion")
-   [The Dreamgrove](https://wowpedia.fandom.com/wiki/Dreamgrove "Dreamgrove"), [Val'sharah](https://wowpedia.fandom.com/wiki/Val%27sharah "Val'sharah") [![Legion](https://static.wikia.nocookie.net/wowpedia/images/f/fd/Legion-Logo-Small.png/revision/latest?cb=20150808040028)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Legion "Legion")
-   [The Fel Hammer](https://wowpedia.fandom.com/wiki/Fel_Hammer "Fel Hammer"), [Mardum](https://wowpedia.fandom.com/wiki/Mardum,_the_Shattered_Abyss "Mardum, the Shattered Abyss") [![Legion](https://static.wikia.nocookie.net/wowpedia/images/f/fd/Legion-Logo-Small.png/revision/latest?cb=20150808040028)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Legion "Legion")
-   [Trueshot Lodge](https://wowpedia.fandom.com/wiki/Trueshot_Lodge "Trueshot Lodge"), [Highmountain](https://wowpedia.fandom.com/wiki/Highmountain "Highmountain") [![Legion](https://static.wikia.nocookie.net/wowpedia/images/f/fd/Legion-Logo-Small.png/revision/latest?cb=20150808040028)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Legion "Legion")
-   [Deliverance Point](https://wowpedia.fandom.com/wiki/Deliverance_Point "Deliverance Point"), [Broken Shore](https://wowpedia.fandom.com/wiki/Broken_Shore "Broken Shore") [![Legion](https://static.wikia.nocookie.net/wowpedia/images/f/fd/Legion-Logo-Small.png/revision/latest?cb=20150808040028)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Legion "Legion")
-   [Magni's Encampment](https://wowpedia.fandom.com/wiki/Magni%27s_Encampment "Magni's Encampment"), [Silithus: The Wound](https://wowpedia.fandom.com/wiki/Silithus:_The_Wound "Silithus: The Wound") [![Battle for Azeroth](https://static.wikia.nocookie.net/wowpedia/images/c/c1/BattleForAzeroth-Logo-Small.png/revision/latest/scale-to-width-down/48?cb=20220421181442)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Battle_for_Azeroth "Battle for Azeroth")
-   [Chamber of Heart](https://wowpedia.fandom.com/wiki/Chamber_of_Heart "Chamber of Heart") [![Battle for Azeroth](https://static.wikia.nocookie.net/wowpedia/images/c/c1/BattleForAzeroth-Logo-Small.png/revision/latest/scale-to-width-down/48?cb=20220421181442)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Battle_for_Azeroth "Battle for Azeroth")
-   [Oribos](https://wowpedia.fandom.com/wiki/Oribos "Oribos") [![Shadowlands](https://static.wikia.nocookie.net/wowpedia/images/9/9a/Shadowlands-Icon-Inline.png/revision/latest/scale-to-width-down/48?cb=20210930025728)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Shadowlands "Shadowlands")
-   [Heart of the Forest](https://wowpedia.fandom.com/wiki/Heart_of_the_Forest "Heart of the Forest"), [Ardenweald](https://wowpedia.fandom.com/wiki/Ardenweald "Ardenweald") [![Shadowlands](https://static.wikia.nocookie.net/wowpedia/images/9/9a/Shadowlands-Icon-Inline.png/revision/latest/scale-to-width-down/48?cb=20210930025728)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Shadowlands "Shadowlands")
-   [The Ring](https://wowpedia.fandom.com/wiki/Ring_(subzone) "Ring (subzone)") [![Night Fae](https://static.wikia.nocookie.net/wowpedia/images/a/ae/Night_Fae_15.png/revision/latest?cb=20210312060936)](https://wowpedia.fandom.com/wiki/Night_Fae_Covenant "Night Fae")[![Shadowlands](https://static.wikia.nocookie.net/wowpedia/images/9/9a/Shadowlands-Icon-Inline.png/revision/latest/scale-to-width-down/48?cb=20210930025728)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Shadowlands "Shadowlands")
-   [Queen's Conservatory](https://wowpedia.fandom.com/wiki/Queen%27s_Conservatory "Queen's Conservatory") [![Night Fae](https://static.wikia.nocookie.net/wowpedia/images/a/ae/Night_Fae_15.png/revision/latest?cb=20210312060936)](https://wowpedia.fandom.com/wiki/Night_Fae_Covenant "Night Fae")[![Shadowlands](https://static.wikia.nocookie.net/wowpedia/images/9/9a/Shadowlands-Icon-Inline.png/revision/latest/scale-to-width-down/48?cb=20210930025728)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Shadowlands "Shadowlands")
-   [Sinfall](https://wowpedia.fandom.com/wiki/Sinfall "Sinfall"), [Revendreth](https://wowpedia.fandom.com/wiki/Revendreth "Revendreth") [![Shadowlands](https://static.wikia.nocookie.net/wowpedia/images/9/9a/Shadowlands-Icon-Inline.png/revision/latest/scale-to-width-down/48?cb=20210930025728)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Shadowlands "Shadowlands")
-   [Seat of the Primus](https://wowpedia.fandom.com/wiki/Seat_of_the_Primus "Seat of the Primus"), [Maldraxxus](https://wowpedia.fandom.com/wiki/Maldraxxus "Maldraxxus") [![Shadowlands](https://static.wikia.nocookie.net/wowpedia/images/9/9a/Shadowlands-Icon-Inline.png/revision/latest/scale-to-width-down/48?cb=20210930025728)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Shadowlands "Shadowlands")
-   [Elysian Hold](https://wowpedia.fandom.com/wiki/Elysian_Hold "Elysian Hold"), [Bastion](https://wowpedia.fandom.com/wiki/Bastion "Bastion") [![Shadowlands](https://static.wikia.nocookie.net/wowpedia/images/9/9a/Shadowlands-Icon-Inline.png/revision/latest/scale-to-width-down/48?cb=20210930025728)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Shadowlands "Shadowlands")
-   [Hero's Rest](https://wowpedia.fandom.com/wiki/Hero%27s_Rest "Hero's Rest"), [Bastion](https://wowpedia.fandom.com/wiki/Bastion "Bastion") [![Shadowlands](https://static.wikia.nocookie.net/wowpedia/images/9/9a/Shadowlands-Icon-Inline.png/revision/latest/scale-to-width-down/48?cb=20210930025728)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Shadowlands "Shadowlands")
-   [Keeper's Respite](https://wowpedia.fandom.com/wiki/Keeper%27s_Respite "Keeper's Respite"), [Korthia](https://wowpedia.fandom.com/wiki/Korthia "Korthia") [![Shadowlands](https://static.wikia.nocookie.net/wowpedia/images/9/9a/Shadowlands-Icon-Inline.png/revision/latest/scale-to-width-down/48?cb=20210930025728)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Shadowlands "Shadowlands")
-   [Haven](https://wowpedia.fandom.com/wiki/Haven "Haven"), [Zereth Mortis](https://wowpedia.fandom.com/wiki/Zereth_Mortis "Zereth Mortis") [![Shadowlands](https://static.wikia.nocookie.net/wowpedia/images/9/9a/Shadowlands-Icon-Inline.png/revision/latest/scale-to-width-down/48?cb=20210930025728)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Shadowlands "Shadowlands")
-   Exile's Hollow, [Zereth Mortis](https://wowpedia.fandom.com/wiki/Zereth_Mortis "Zereth Mortis") [![Shadowlands](https://static.wikia.nocookie.net/wowpedia/images/9/9a/Shadowlands-Icon-Inline.png/revision/latest/scale-to-width-down/48?cb=20210930025728)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Shadowlands "Shadowlands")
-   Pilgrim's Grace, [Zereth Mortis](https://wowpedia.fandom.com/wiki/Zereth_Mortis "Zereth Mortis") [![Shadowlands](https://static.wikia.nocookie.net/wowpedia/images/9/9a/Shadowlands-Icon-Inline.png/revision/latest/scale-to-width-down/48?cb=20210930025728)](https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Shadowlands "Shadowlands")

| 
-   [v](https://wowpedia.fandom.com/wiki/Template:Territory "Template:Territory")
-   [e](https://wowpedia.fandom.com/wiki/Template:Territory?action=edit)

[Zone](https://wowpedia.fandom.com/wiki/Zone "Zone") Territory types

 |
| --- |
|  |
| 

-   [Alliance](https://wowpedia.fandom.com/wiki/Alliance_territory "Alliance territory")
-   [Combat zone](https://wowpedia.fandom.com/wiki/Combat_zone "Combat zone")
-   [Contested](https://wowpedia.fandom.com/wiki/Contested_territory "Contested territory")
-   [Horde](https://wowpedia.fandom.com/wiki/Horde_territory "Horde territory")
-   [No-fly zone](https://wowpedia.fandom.com/wiki/No-fly_zone "No-fly zone")
-   **Sanctuary**



 |

Others like you also viewed